### ISSUE TITLE
Returning None where messagelist dict expected

### ISSUE THREAD

**Issue by sigma914** [OfflineIMAP/offlineimap#161]
I've found and error in v6.5.7-rc2

This seems to be caused by setting messagelist to None to invalidate a cache and then not checking it in various places.

    ERROR: ERROR in syncfolder for <snip> folder Sent: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 466, in syncfolder
        remotefolder.syncmessagesto(localfolder, statusfolder)
      File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 893, in syncmessagesto
        action(dstfolder, statusfolder)
      File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 787, in __syncmessagesto_delete
        statusfolder.getmessageuidlist())
      File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 277, in getmessageuidlist
        return self.getmessagelist().keys()
    AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by nicolas33** [comment]
Fixed in 9e63fa3.
