### ISSUE TITLE
offlineimap+dovecot OperationalError: unable to open database file

### ISSUE THREAD

**Issue by noorul** [OfflineIMAP/offlineimap#167]
I am using offlineimap version 6.5.5 on Mac OS X Yosemite and I get the following when I try to sync.
 
ERROR: ERROR in syncfolder for Noorul folder INBOX: Traceback (most recent call last):
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/accounts.py", line 399, in syncfolder
    statusrepos.getsep()))
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/repository/LocalStatus.py", line 106, in getfolder
    self.import_other_backend(folder)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/repository/LocalStatus.py", line 69, in import_other_backend
    folderbk = dic['class'](folder.name, repobk)
  File "/usr/local/Cellar/offline-imap/6.5.6/libexec/offlineimap/folder/LocalStatusSQLite.py", line 59, in __init__
    self.connection = sqlite.connect(self.filename, check_same_thread = False)
OperationalError: unable to open database file

I did some investigation and I observe the following.

1. The same offlineimaprc configuration works on offlineimap 6.3.5 on debian along with dovecot
2. It looks like recent version of offlineimap is not creating status db for folders that already exist in destination.
3. I thought this issue was just with my INBOX folder as dovecot creates this by default. By it looks like if I delete status db for of already synced folder, I get the same error for that too.

**Comment by noorul** [comment]
A temporary non-ideal solution, that I found is to translate INBOX mailbox to GmailInbox and vice versa using nametrans which is actually bad.

**Comment by nicolas33** [comment]
Looks like a dup of #133. This is fixed in more recent version.
