### ISSUE TITLE
Error unpacking value

### ISSUE THREAD

**Issue by buster** [OfflineIMAP/offlineimap#173]
From the current next branch, i got this error (which lead to offlineimap stopping altogether):

```
Feb 23 10:13:31 Fry offlineimap.py[5119]: *** Finished account 'Office' in 0:11
Feb 23 10:14:04 Fry offlineimap.py[5119]: Exception in thread outlook.office365.com handler:
Feb 23 10:14:04 Fry offlineimap.py[5119]: Traceback (most recent call last):
Feb 23 10:14:04 Fry offlineimap.py[5119]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Feb 23 10:14:04 Fry offlineimap.py[5119]: self.run()
Feb 23 10:14:04 Fry offlineimap.py[5119]: File "/usr/lib/python2.7/threading.py", line 763, in run
Feb 23 10:14:04 Fry offlineimap.py[5119]: self.__target(*self.__args, **self.__kwargs)
Feb 23 10:14:04 Fry offlineimap.py[5119]: File "/home/buster/sources/offlineimap/offlineimap/imaplib2.py", line 1737, in _handler
Feb 23 10:14:04 Fry offlineimap.py[5119]: rqb.abort_tb(typ, val, tb)
Feb 23 10:14:04 Fry offlineimap.py[5119]: File "/home/buster/sources/offlineimap/offlineimap/imaplib2.py", line 165, in abort_tb
Feb 23 10:14:04 Fry offlineimap.py[5119]: self.deliver(None)
Feb 23 10:14:04 Fry offlineimap.py[5119]: File "/home/buster/sources/offlineimap/offlineimap/imaplib2.py", line 188, in deliver
Feb 23 10:14:04 Fry offlineimap.py[5119]: self.callback((response, self.callback_arg, self.aborted))
Feb 23 10:14:04 Fry offlineimap.py[5119]: File "/home/buster/sources/offlineimap/offlineimap/imaplib2.py", line 1400, in _command_completer
Feb 23 10:14:04 Fry offlineimap.py[5119]: typ, val = error
Feb 23 10:14:04 Fry offlineimap.py[5119]: ValueError: too many values to unpack
Feb 23 10:14:31 Fry offlineimap.py[5119]: *** Processing account Office
```

**Comment by nicolas33** [comment]
This is definetly a bug from imaplib2. I'm forwarding to the imaplib2 mailing list.

**Comment by nicolas33** [comment]
Relevant logs for further digging:
```
Copy message from Local:SMS:
 [imap]:   01:28.22 Copy message from Local:SMS LOGOUT:FKFI41.ready.wait
imap.gmail.com reader:
 [imap]:   01:28.25 imap.gmail.com reader poll => [(4, 1)]
 [imap]:   01:28.25 imap.gmail.com reader rcvd 57
 [imap]:   01:28.25 imap.gmail.com reader < * BYE LOGOUT Requested\r\n
 [imap]:   01:28.25 imap.gmail.com reader < FKFI41 OK 73 good day (Success)\r\n
imap.gmail.com handler:
 [imap]:   01:28.25 imap.gmail.com handler untagged_responses[BYE] 0 += ["LOGOUT Requested"]
 [imap]:   01:28.25 imap.gmail.com handler BYE response: LOGOUT Requested
imap.gmail.com reader:
 [imap]:   01:28.25 imap.gmail.com reader poll => []
 [imap]:   01:28.25 imap.gmail.com reader finished
imap.gmail.com handler:
 [imap]:   01:28.26 imap.gmail.com handler terminating: 'connection terminated'
imap.gmail.com writer:
 [imap]:   01:28.26 imap.gmail.com writer finished
Copy message from Local:SMS:
 [imap]:   01:28.26 Copy message from Local:SMS ["<type 'exceptions.TypeError'>: raise: arg 3 must be a traceback or None"]
 [imap]:   01:28.26 Copy message from Local:SMS _close_threads
 [imap]:   01:28.26 Copy message from Local:SMS call shutdown
imap.gmail.com handler:
 [imap]:   01:28.26 imap.gmail.com handler LOGOUT:FKFI41.ready.set
 [imap]:   01:28.26 imap.gmail.com handler state_change_free.set
 [imap]:   01:28.26 imap.gmail.com handler finished
Copy message from Local:SMS:
 [imap]:   01:28.26 Copy message from Local:SMS state_change_pending.release
 [imap]:   01:28.26 Copy message from Local:SMS connection closed
 [imap]:   01:28.26 Copy message from Local:SMS _get_untagged_response(BYE) => ['LOGOUT Requested']
 Establishing connection to imap.gmail.com:993
 [imap]:   01:28.26 Copy message from Local:SMS imaplib2 version 2.37
 [imap]:   01:28.26 Copy message from Local:SMS imaplib2 debug level 5, buffer level 3
 ERROR: Saving msg ([unknown message-id]) folder 'SMS', repo 'Remote'failed (error). Server responded: APPEND command error: BAD ['Invalid Arguments: Unable to parse message']. Data: FKFI39 APPEND SMS (\Seen) {1}

Traceback:
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 711, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Gmail.py", line 195, in savemessage
    return super(GmailFolder, self).savemessage(uid, content, flags, rtime)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 576, in savemessage
    imaputil.flagsmaildir2imap(flags), date, content)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 629, in append
    return self._simple_command(name, mailbox, flags, date_time, **kw)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1620, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1386, in _command_complete
    raise self.error('%s command error: %s %s. Data: %.100s' % (rqb.name, typ, dat, rqb.data))

```

This looks like a bug in imaplib2, I'm forwarding to the maintainer.

**Comment by nicolas33** [comment]
https://sourceforge.net/p/imaplib2/bugs/5/

**Comment by johnmolyneux** [comment]
There is no "abort_tb" in my current imaplib2.py code, so I'd guess that this is a bug in local amendments to the original.

Sounds like a good idea though - I'd be interested in a patch once the bugs are ironed out :-)

Piers lauder

**Comment by nicolas33** [comment]
@johnmolyneux: Oh, I totally forgot we had some local changes, sorry. I'm attaching the patches as sorted out by `git format-patch`. Let me know if you'd rather them differently or through another channel.

https://gist.github.com/nicolas33/637b6d7457e387f0af95

**Comment by nicolas33** [comment]
Notice it still hold the bug, for now. I don't know if I'll fix that or revert the patches.

**Comment by nicolas33** [comment]
@konvpalto : would you mind to fix it?

**Comment by johnmolyneux** [comment]
The latest version of imaplib2.py (2.29) has been converted to be python3 compatible, so I'm just interested in the abort_tb patches - once debugged. Thanks!

**Comment by nicolas33** [comment]
Bumped to imaplib2 v2.41.
