### ISSUE TITLE
maxage not taking date

### ISSUE THREAD

**Issue by naveen1336** [OfflineIMAP/offlineimap#210]
return self._get(section, int, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '2015-05-01'

  invalid literal for int() with base 10: '2015-05-01'
ERROR: ERROR in syncfolder for GMail80 folder Starred: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 442, in syncfolder
    localfolder.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/GmailMaildir.py", line 69, in cachemessagelist
    self.messagelist = self._scanfolder()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Maildir.py", line 162, in _scanfolder
    "maxage", None)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/CustomConfig.py", line 47, in getdefaultint
    return self.getint(*(section, option) + args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))
ValueError: invalid literal for int() with base 10: '2015-05-01'

  invalid literal for int() with base 10: '2015-05-01'
ERROR: ERROR in syncfolder for GMail80 folder Trash: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 442, in syncfolder
    localfolder.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/GmailMaildir.py", line 69, in cachemessagelist
    self.messagelist = self._scanfolder()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Maildir.py", line 162, in _scanfolder
    "maxage", None)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/CustomConfig.py", line 47, in getdefaultint
    return self.getint(*(section, option) + args, **kwargs)
  File "/usr/lib/python2.7/ConfigParser.py", line 359, in getint
    return self._get(section, int, option)
  File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
    return conv(self.get(section, option))

**Comment by nicolas33** [comment]
OfflineIMAP version?

**Comment by nicolas33** [comment]
No response, no reports from other users and maxage had lot of changes recently: closing.
