### ISSUE TITLE
Can't save a zero byte message

### ISSUE THREAD

**Issue by emmanuelgeoffray** [OfflineIMAP/offlineimap#216]
Hey there,
I have an issue with offlineimap crashing with the server replying "Can't save a zero byte message"
Any idea why would offlineimap try to sync a zero byte message?
My hard drive was ful lately, do you think the issue started from there?

Here is the log 
```
INFO:OfflineImap:Syncing Sent: IMAP -> Maildir
Copy message -1 (1 of 2) MyLocal:Sent -> MyGandi
INFO:OfflineImap:Copy message -1 (1 of 2) MyLocal:Sent -> MyGandi
Syncing Sent Messages: IMAP -> Maildir
INFO:OfflineImap:Syncing Sent Messages: IMAP -> Maildir
Thread 'Folder Sent [acc: MyAccount]' terminated with exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 158, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/offlineimap/accounts.py", line 458, in syncfolder
    localfolder.syncmessagesto(remotefolder, statusfolder)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 549, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 432, in syncmessagesto_copy
    register = 0)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 358, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 554, in savemessage
    raise OfflineImapError(msg, OfflineImapError.ERROR.REPO)
OfflineImapError: Saving msg in folder 'Sent', repository 'MyGandi' failed (abort). Server responded: NO ["Can't save a zero byte message."]



Last 15 debug messages logged for Folder Sent [acc: MyAccount] prior to exception:
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6096'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6097'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6098'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6099'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6100'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6101'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6102'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6103'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6104'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6105'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6106'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6107'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6108'}
imap: Write mail 'Sent:-1' with flags set(['S'])
imap: savemessage: date: "09-Jul-2015 15:11:17 +0100", content: ''
WARNING:OfflineImap:Thread 'Folder Sent [acc: MyAccount]' terminated with exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 158, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/offlineimap/accounts.py", line 458, in syncfolder
    localfolder.syncmessagesto(remotefolder, statusfolder)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 549, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 432, in syncmessagesto_copy
    register = 0)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 358, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 554, in savemessage
    raise OfflineImapError(msg, OfflineImapError.ERROR.REPO)
OfflineImapError: Saving msg in folder 'Sent', repository 'MyGandi' failed (abort). Server responded: NO ["Can't save a zero byte message."]



Last 15 debug messages logged for Folder Sent [acc: MyAccount] prior to exception:
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6096'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6097'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6098'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6099'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6100'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6101'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6102'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6103'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6104'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6105'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6106'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6107'}
imap: options2hash returning: {'FLAGS': '(\\Seen)', 'UID': '6108'}
imap: Write mail 'Sent:-1' with flags set(['S'])
imap: savemessage: date: "09-Jul-2015 15:11:17 +0100", content: ''
```

**Comment by nicolas33** [comment]
AFAIR offlineimap won't check for message size which is a good thing IMO.

I can't tell what's the root cause. You have to remove the offending mail manually.

**Comment by johnmastro** [comment]
You can find all such files with `find`:

```
$ cd YOUR_MAILDIR
$ find . -type f -size 0b
```

And you could even delete them all:

```
$ cd YOUR_MAILDIR
$ find . -type f -size 0b -exec rm {} \;
```

**Comment by emmanuelgeoffray** [comment]
Sorry I didn't read your replay @johnmastro 
Thank you very much, that worked!

**Comment by varac** [comment]
> AFAIR offlineimap won't check for message size which is a good thing IMO.

I disagree here - If offlineimap syncs 0 bytes msgs *and* throws an error afterward for such mails there's obviously sth wrong. It would be good to find the root cause of this bug and fix it imo.
