### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by gerroon** [OfflineIMAP/offlineimap#239]
I am on Debian Wheezy 32bit Python27 OImap  6.5.6.1-devel

It syncs most of my accounts except this one which is on am different server. 

ERROR: Exceptions occurred during the run!
 ERROR: ERROR in syncfolder for myACCOUNT folder .Trash: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 399, in syncfolder
    statusrepos.getsep()))
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 105, in getfolder
    self.import_other_backend(folder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 75, in import_other_backend
    folderbk.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/LocalStatusSQLite.py", line 187, in cachemessagelist
    labels = set([lb.strip() for lb in row[3].split(',') if len(lb.strip()) > 0])
AttributeError: 'NoneType' object has no attribute 'split'

  'NoneType' object has no attribute 'split'
 ERROR: ERROR in syncfolder for myACCOUNT folder INBOX: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 399, in syncfolder
    statusrepos.getsep()))
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 105, in getfolder
    self.import_other_backend(folder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 75, in import_other_backend
    folderbk.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/LocalStatusSQLite.py", line 187, in cachemessagelist
    labels = set([lb.strip() for lb in row[3].split(',') if len(lb.strip()) > 0])
AttributeError: 'NoneType' object has no attribute 'split'

  'NoneType' object has no attribute 'split'
 ERROR: ERROR in syncfolder for myACCOUNT folder Sent: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 399, in syncfolder
    statusrepos.getsep()))
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 105, in getfolder
    self.import_other_backend(folder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 75, in import_other_backend
    folderbk.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/LocalStatusSQLite.py", line 187, in cachemessagelist
    labels = set([lb.strip() for lb in row[3].split(',') if len(lb.strip()) > 0])
AttributeError: 'NoneType' object has no attribute 'split'

  'NoneType' object has no attribute 'split'
 ERROR: ERROR in syncfolder for myACCOUNT folder Trash: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/accounts.py", line 399, in syncfolder
    statusrepos.getsep()))
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 105, in getfolder
    self.import_other_backend(folder)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/repository/LocalStatus.py", line 75, in import_other_backend
    folderbk.cachemessagelist()
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/LocalStatusSQLite.py", line 187, in cachemessagelist
    labels = set([lb.strip() for lb in row[3].split(',') if len(lb.strip()) > 0])
AttributeError: 'NoneType' object has no attribute 'split'

  'NoneType' object has no attribute 'split'

**Comment by nicolas33** [comment]
Please try last stable v6.5.7.

**Comment by gerroon** [comment]
Hi

Thanks for the reply. I will try but how do I get the 6.5.7 ?

thanks

**Comment by nicolas33** [comment]
http://offlineimap.org/doc/FAQ.html#where-do-i-get-offlineimap

**Comment by gerroon** [comment]
Hi

I downloaded the tar that is tagged as 6.5.7, and I still have the same issue. However bin/offlineimap --version still prints 6.5.6.1-devel.

I am not sure if the version is wrong or the tagged tar is pointing to the wrong zip.

**Comment by gerroon** [comment]
@nicolas33 
Can you please tell me how I can download 6.5.7? As I explained in the previous post the dev versions tagged as 6.5.7 are still 6.5.6.1-devel and I am desperately needing ton get my mails from the server ;( 

thanks

**Comment by nicolas33** [comment]
http://offlineimap.org/

**Comment by gerroon** [comment]
@nicolas33 

That is already what I did. 

Here is the zip I just downloaded.
https://codeload.github.com/OfflineIMAP/offlineimap/zip/v6.5.7 

I unzipped it. And then I typed in the "bin" folder of the unzipped 6.5.7
$ ./offlineimap --version
6.5.5

Not sure why I am having hard time getting my message across.

**Comment by jschwab** [comment]
When you cd into `bin` and execute `./offlineimap`, you are runnning the system-wide version of offlineimap, That's not telling you anything about what is in the ZIP file.

In the root of the zipfile, if you were to do

    offlineimap-6.5.7$  ./bin/offlineimap --version

you should see

    6.5.7

**Comment by gerroon** [comment]
$ ./bin/offlineimap --version
6.5.5

**Comment by jschwab** [comment]
Maybe I'm confused about what looks where.

At any rate, what does the file (relative to the zipfile root) `offlineimap/__init__.py` say?  I believe that's where the version string is specified.  The fourth line of that file for me is

    __version__     = "6.5.7"

**Comment by gerroon** [comment]
Hi
Interesting, __init__.py is 6.5.7. I am notn sure what to make of it.

**Comment by nicolas33** [comment]
Retry after a `make clean`. This *might* help.

**Comment by nicolas33** [comment]
My best guess is that your PYTHONPATH is screwed-up.
