### ISSUE TITLE
UnicodeDecodeError happens when mutt sets flag on Gmail

### ISSUE THREAD

**Issue by yang-ling** [OfflineIMAP/offlineimap#282]
## Reproduce steps

1. Setup gmail account configuration
2. Synchronize by offlineimap. The first synchronization is OK.
3. Open mutt.
4. Set flag on a message. The default key binding is <ESC>f and the function is `flag-message`
5. The message should be marked with a `!`
6. Synchronize by offlineimap again. Error may happen here but sometimes it is also OK.
7. Do some operation in mutt, such as unflag message, delete message.
8. Synchronize by offlineimap again. Error happens here.

## Error message

The command is `offlineimap -d imap maildir thread`. No `autorefresh` in configuration file

I ran this command twice.

The first time error is

```
Adding flag S to 1 messages on 所有邮件
ERROR: Syncing folder [Gmail]/&YkBnCZCuTvY- [acc: yangling1984gmail]
  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
ERROR: ERROR in syncfolder for yangling1984gmail folder 所有邮件: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 567, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1000, in __syncmessagesto_flags
    self.ui.deletingflags(uids, flag, dstfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 404, in deletingflags
    ", ".join(flags), len(uidlist), dest))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
Calling hook: ~/.config/offlineimap/offlineimaphook.sh
Hook stdout: Processed 2 total files in almost no time.[K
No new mail. Detected 7 file renames.

Hook stderr:

Hook return code: 0
*** Finished account 'yangling1984gmail' in 0:43
ERROR: Exceptions occurred during the run!
ERROR: Syncing folder [Gmail]/&YkBnCZCuTvY- [acc: yangling1984gmail]
  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1000, in __syncmessagesto_flags
    self.ui.deletingflags(uids, flag, dstfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 404, in deletingflags
    ", ".join(flags), len(uidlist), dest))

ERROR: ERROR in syncfolder for yangling1984gmail folder 所有邮件: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 567, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1000, in __syncmessagesto_flags
    self.ui.deletingflags(uids, flag, dstfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 404, in deletingflags
    ", ".join(flags), len(uidlist), dest))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

The second time error is

```
Syncing messages Gmail[[Gmail]/&YkBnCZCuTvY-] -> GmailMaildir[所有邮件]
ERROR: Syncing folder [Gmail]/&YkBnCZCuTvY- [acc: yangling1984gmail]
  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
['  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto\n    action(dstfolder, statusfolder)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1000, in __syncmessagesto_flags\n    self.ui.deletingflags(uids, flag, dstfolder)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 404, in deletingflags\n    ", ".join(flags), len(uidlist), dest))\n']
ERROR: ERROR in syncfolder for yangling1984gmail folder 所有邮件: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 567, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1000, in __syncmessagesto_flags
    self.ui.deletingflags(uids, flag, dstfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 404, in deletingflags
    ", ".join(flags), len(uidlist), dest))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
Syncing &ZTZjbg-: Gmail -> GmailMaildir
...
...

*** Finished account 'yangling1984gmail' in 1:01
ERROR: Exceptions occurred during the run!
ERROR: Syncing folder [Gmail]/&YkBnCZCuTvY- [acc: yangling1984gmail]
  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1000, in __syncmessagesto_flags
    self.ui.deletingflags(uids, flag, dstfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 404, in deletingflags
    ", ".join(flags), len(uidlist), dest))

ERROR: ERROR in syncfolder for yangling1984gmail folder 所有邮件: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 567, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1000, in __syncmessagesto_flags
    self.ui.deletingflags(uids, flag, dstfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 404, in deletingflags
    ", ".join(flags), len(uidlist), dest))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

  'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
```

The difference of the 2 errors is this line:

`Adding flag S to 1 messages on 所有邮件`

I guess the `flag S` is set by mutt, which is `!` in mutt. I guess it is `Starred` in Gmail

## Environment information

* OS: Archlinux
* OfflineIMAP: 6.6.0 from [AUR](https://aur4.archlinux.org/packages/offlineimap-git/)
* mutt: 1.5.24

I feel this issue OfflineIMAP/offlineimap#59 is related to mine.

Tell me if more information is required.

Thanks in advance!

**Comment by nicolas33** [comment]
Unicode in folder names is not supported. Offlineimap has assumptions they must be IMAP UTF-7 encoded.
