### ISSUE TITLE
GSSAPI/Kerberos authentication broken

### ISSUE THREAD

**Issue by iliastsi** [OfflineIMAP/offlineimap#332]
It has been reported to the [Debian bug tracking system]( https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=810119
) that GSSAPI/Kerberos authentication is broken in the latest version of OfflineIMAP.

I am not using Kerberos authentication myself, so I can neither debug this, nor offer more information. I am just opening an issue here, in case someone exhibits the same problem and can provide more information.

### General informations

- OfflineIMAP version: 6.7.0

### Log error

```
GSSAPI authentication failed: AUTHENTICATE command error: BAD ['Authentication aborted by client.']. Data: IDBA2 AUTHENTICATE GSSAPI

ERROR: ERROR in syncfolder for honk.sigxcpu.org folder admin.spam: Traceback (most recent call last):
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 561, in syncfolder
    check_uid_validity(localfolder, remotefolder, statusfolder)
  File "/usr/share/offlineimap/offlineimap/accounts.py", line 417, in check_uid_validity
    if not remotefolder.check_uidvalidity():
  File "/usr/share/offlineimap/offlineimap/folder/Base.py", line 207, in check_uidvalidity
    return self.get_saveduidvalidity() == self.get_uidvalidity()
  File "/usr/share/offlineimap/offlineimap/folder/IMAP.py", line 103, in get_uidvalidity
    imapobj = self.imapserver.acquireconnection()
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 495, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 397, in __authn_helper
    if func(imapobj):
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 321, in __authn_plain
    imapobj.authenticate('PLAIN', self.__plainhandler)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 705, in authenticate
    typ, dat = self._simple_command('AUTHENTICATE', mechanism.upper())
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 1695, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 1421, in _command
    literal = literator(data, rqb)
  File "/usr/lib/python2.7/dist-packages/imaplib2.py", line 2286, in process
    ret = self.mech(self.decode(data))
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 203, in __plainhandler
    passwd = self.__getpassword()
  File "/usr/share/offlineimap/offlineimap/imapserver.py", line 153, in __getpassword
    self.passworderror)
  File "/usr/share/offlineimap/offlineimap/ui/UIBase.py", line 257, in getpass
    raise NotImplementedError("Prompting for a password is not supported"
NotImplementedError: Prompting for a password is not supported in this UI backend.
```

**Comment by nicolas33** [comment]
This is with version 6.6.1+dfsg1-1. What was the previous version?
It is currently trying PLAIN authentication. What's the configuration file?

**Comment by shlevy** [comment]
I get a similar error, using 6.7.0:

```shell
$ offlineimap
OfflineIMAP 6.7.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Account sync main:
 *** Processing account main
 Establishing connection to imap.exchange.mit.edu:993
 GSSAPI authentication failed: The AUTH protocol exchange was canceled by the client.
Enter password for account 'main-remote':
```

**Comment by nicolas33** [comment]
@shlevy Please, run a session with IMAP debug logs enabled.

**Comment by shlevy** [comment]
Ah, sorry, was a configuration error on my end.

**Comment by kcr** [comment]
I can duplicate this, but it works if I turn on -d imap

**Comment by nicolas33** [comment]
@kcr Open a new issue, please.

**Comment by diego-treitos** [comment]
In case anybody lands here searching for the error `NotImplementedError: Prompting for a password is not supported in this UI backend.`, please be sure to have installed the `pinentry` packages. That solved it for me.

**Comment by chris001** [comment]
@nicolas33 
We should add `pinentry` package to `requirements.txt` for support of the `gssapi` authentication feature, no?

**Comment by nicolas33** [comment]
I didn't know about pinentry. If this can solve issues I'm fine with the change, yes.

**Comment by diego-treitos** [comment]
> @nicolas33
> We should add `pinentry` package to `requirements.txt` for support of the `gssapi` authentication feature, no?

Let me clarify. I don't think there is a python package called `pinentry` or related to it. I installed system packages related to `pinentry`. In my case, I use debian and it has these `pinentry` packages available:

```
pinentry-curses
pinentry-doc
pinentry-fltk
pinentry-gnome3
pinentry-gtk2
pinentry-qt
pinentry-qt4
pinentry-tty
pinentry-x2go
```

If your environment is GTK based, you probably want:

```
pinentry-curses
pinentry-gnome3
pinentry-gtk2
pinentry-tty
```

If it is a QT environment, you probably want

```
pinentry-curses
pinentry-qt
pinentry-qt4
pinentry-tty
```
