### ISSUE TITLE
using '--info' command line option and 'ui = xxx' in config file

### ISSUE THREAD

**Issue by heavytull** [OfflineIMAP/offlineimap#352]
#### General informations

- offlineimap version (`offlineimap -V`): 6.7.0
- Python version: 2.7
- server name or domain: gmail.com
- CLI options: ???

#### Configuration file offlineimaprc
ui = ttyui | Blinkenlights | ...
```
using '--info' command line option seems to overhide the 'ui = ...' setting in the config file.
when running offllineimap with '--info' it doesn't prompt for a password. Below is the output. When not using '--info' offlineimap prompts for my password after the XOAUTH2 error. The most interesting part is at the bottom of the output.

OUTPUT : 
OfflineIMAP 6.7.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Debug mode: Forcing to singlethreaded.
Now debugging for maildir: Maildir repository debugging
Now debugging for : Other offlineimap related sync messages
[maildir]: MaildirRepository initialized, sep is '.'
Remote repository 'magmremote': type 'IMAP'
Host: imap.gmail.com Port: 993 SSL: True
Establishing connection to imap.gmail.com:993
XOAUTH2 authentication failed: AUTHENTICATE command error: BAD ['Client aborted A[34/1852]
TE command. rn9mb48415026wjb']. Data: EFHK2 AUTHENTICATE XOAUTH2

Traceback (most recent call last):
  File "/usr/bin/offlineimap", line 23, in <module>
    oi.run()
  File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 53, in run
    self.__serverdiagnostics(options)
  File "/usr/lib/python2.7/site-packages/offlineimap/init.py", line 436, in __serverdiagno
stics
    account.serverdiagnostics()
File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 197, in s[23/1852]
nostics
    self.ui.serverdiagnostics(remote_repo, 'Remote')
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 439, in serverdia
gnostics
    conn = repository.imapserver.acquireconnection()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 511, in acquirec
onnection
    self.__authn_helper(imapobj)
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 411, in __authn_
helper
    if func(imapobj):
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 335, in[11/1852]
plain
    imapobj.authenticate('PLAIN', self.__plainhandler)
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplib2.py", line 704, in authentica
te
    typ, dat = self._simple_command('AUTHENTICATE', mechanism.upper())
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplib2.py", line 1691, in _simple_c
ommand
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplib2.py", line 1417, in _command
    literal = literator(data, rqb)
File "/usr/lib/python2.7/site-packages/offlineimap/imaplib2.py", line 2282, in p[0/1852]
    ret = self.mech(self.decode(data))
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 211, in __plainh
andler
    passwd = self.__getpassword()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 161, in __getpas
sword
    self.passworderror)
  File "/usr/lib/python2.7/site-packages/offlineimap/ui/UIBase.py", line 260, in getpass
    raise NotImplementedError("Prompting for a password is not supported"
NotImplementedError: Prompting for a password is not supported in this UI backend.

**Comment by nicolas33** [comment]
Changed from `basic` to `ttyui`. Thank you for the report.
