### ISSUE TITLE
GMail repository fails to synchronize on python 2.7

### ISSUE THREAD

**Issue by jpalus** [OfflineIMAP/offlineimap#363]
Relevant error which appears to be caused by removing inheritance from object in BaseRepository (88e8a48):
```
Thread 'Account sync Gmail' terminated with exception:
Traceback (most recent call last):
  File "/usr/share/python2.7/site-packages/offlineimap/threadutil.py", line 163, in run
  File "/usr/lib64/python2.7/threading.py", line 754, in run
  File "/usr/share/python2.7/site-packages/offlineimap/accounts.py", line 256, in syncrunner
  File "/usr/share/python2.7/site-packages/offlineimap/repository/__init__.py", line 84, in __new__
  File "/usr/share/python2.7/site-packages/offlineimap/repository/Gmail.py", line 39, in __init__
  File "/usr/share/python2.7/site-packages/offlineimap/repository/IMAP.py", line 41, in __init__
  File "/usr/share/python2.7/site-packages/offlineimap/imapserver.py", line 96, in __init__
  File "/usr/share/python2.7/site-packages/offlineimap/repository/Gmail.py", line 48, in gethost
TypeError: must be type, not classobj


Last 2 debug messages logged for Account sync Gmail prior to exception:
```

**Comment by nicolas33** [comment]
My bad. I forgot the parent. Does above patch fixes the issue?

**Comment by jpalus** [comment]
Works fine, thanks.

**Comment by nicolas33** [comment]
Applied. Thank you much @jpalus !

**Comment by nicolas33** [comment]
v7.0.4 is out.
