### ISSUE TITLE
Error syncing on Mac OS X

### ISSUE THREAD

**Issue by captainepoch** [OfflineIMAP/offlineimap#366]
#### General informations

- system/distribution (with version): Mac OS X, El Capitán 11.6
- offlineimap version (`offlineimap -V`): offlineimap v7.0.3, imaplib2 v2.55 (bundled)
- Python version: 2.7.12 (Homebrew)
- server name or domain: localhost
- CLI options: offlineimap

#### Configuration file offlineimaprc

```
[general]
accounts = personal
pythonfile = ~/.mutt/scripts/pykeyring.py

[Account personal]
localrepository = personal_local
remoterepository = personal_remote
status_backend = sqlite
maxage = 30

[Repository personal_local]
type = Maildir
localfolders = ~/mail/personal
nametrans = lambda folder: {'inbox': 'INBOX', 'sent': '[Gmail]/Enviados',}.get(folder, folder)

[Repository personal_remote]
type = Gmail
ssl = yes
remoteuser = MAIL@gmail.com
remotepasseval = keyring.get_password('mutt', 'MAIL@gmail.com')
# GMail changes fingerprint
sslcacertfile = /usr/local/etc/openssl/cert.pem
nametrans = lambda folder: {'INBOX': 'inbox', '[Gmail]/Enviados': 'sent',}.get(folder, folder)
folderfilter = lambda folder: folder in ['INBOX', '[Gmail]/Enviados']
```

#### pythonfile (if any)

I use ```keyring``` from pip to manage my account password.

```
import keyring
```

#### Logs, error

```
OfflineIMAP 7.0.3
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Thread 'Account sync personal' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/offlineimap/7.0.3/libexec/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/offlineimap/7.0.3/libexec/offlineimap/accounts.py", line 256, in syncrunner
    self.remoterepos = Repository(self, 'remote')
  File "/usr/local/Cellar/offlineimap/7.0.3/libexec/offlineimap/repository/__init__.py", line 84, in __new__
    return repo(name, account)
  File "/usr/local/Cellar/offlineimap/7.0.3/libexec/offlineimap/repository/Gmail.py", line 39, in __init__
    IMAPRepository.__init__(self, reposname, account)
  File "/usr/local/Cellar/offlineimap/7.0.3/libexec/offlineimap/repository/IMAP.py", line 41, in __init__
    self.imapserver = imapserver.IMAPServer(self)
  File "/usr/local/Cellar/offlineimap/7.0.3/libexec/offlineimap/imapserver.py", line 96, in __init__
    None if self.preauth_tunnel else repos.gethost()
  File "/usr/local/Cellar/offlineimap/7.0.3/libexec/offlineimap/repository/Gmail.py", line 48, in gethost
    return super(GmailRepository, self).gethost()
TypeError: super() argument 1 must be type, not classobj


Last 2 debug messages logged for Account sync personal prior to exception:
thread: Register new thread 'Account sync personal' (account 'personal')
imap: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
```

#### Steps to reproduce the error

- Using my `.offlineimaprc`, just run `offlineimap` from cli.

**Comment by trey-pindrop** [comment]
Got it here, too.  Works on my Arch Linux system (also running 7.0.3)

**Comment by ggarlic** [comment]
it's already fixed on branch next:

https://github.com/OfflineIMAP/offlineimap/commit/b19eaebad1e9ae58ed8db028b65c5391cab1271a

you can apply it on your mac, just one line changed

**Comment by adam8157** [comment]
Great thanks to @ggarlic 👍

**Comment by asethwright** [comment]
Thanks so much for your work.

**Comment by ggarlic** [comment]
@asethwright it's not my work, i just copy the link here  😄
all credits goes to @nicolas33

**Comment by nicolas33** [comment]
Dups #363.
