### ISSUE TITLE
Cannot use xoauth2_client_id_eval. 'str' object is not callable

### ISSUE THREAD

**Issue by darnir** [OfflineIMAP/offlineimap#372]
#### General informations

- system/distribution (with version): Arch Linux
- offlineimap version (`offlineimap -V`): offlineimap v7.0.5, imaplib2 v2.55 (bundled)
- Python version: 3.5.2
- server name or domain: 
- CLI options: 

#### Configuration file offlineimaprc

```
[Repository gmail-remote]
type = Gmail
remoteuser = <gmail id>
auth_mechanisms = XOAUTH2
oauth2_client_id_eval = get_auth('client_id')
oauth2_client_secret_eval = get_auth('client_secret')
oauth2_request_url = https://accounts.google.com/o/oauth2/token
oauth2_refresh_token = <refresh_token...>
```

#### pythonfile (if any)

```
#! /usr/bin/env python2
from subprocess32 import check_output


def get_pass(account):
    return check_output("pass Mail/" + account, shell=True).splitlines()[0]


def get_auth(account):
    output = check_output("pass Mail/" + account, shell=True)
    return output
```

#### Logs, error

```
OfflineIMAP 7.0.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Debug mode: Forcing to singlethreaded.
Now debugging for imap: IMAP protocol debugging
Now debugging for : Other offlineimap related sync messages
[imap]: Using authentication mechanisms ['XOAUTH2']
ERROR: 'str' object is not callable
ERROR: Exceptions occurred during the run!
ERROR: 'str' object is not callable
```

I see that the configuration file states that the output of xoauth2_client_id_eval should be bytes. But the documentation for check_output() states that it returns bytes. So what else should I be doing?

**Comment by nicolas33** [comment]
Not stack trace?
Is this only when using `-d imap`? (Please, provide the CLI options, BTW).

**Comment by darnir** [comment]
Stack trace is visible when I don't use the `-d imap` option.

```
Thread 'Account sync gmail' terminated with exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 256, in syncrunner
    self.remoterepos = Repository(self, 'remote')
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/__init__.py", line 84, in __new__
    return repo(name, account)
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/Gmail.py", line 39, in __init__
    IMAPRepository.__init__(self, reposname, account)
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 41, in __init__
    self.imapserver = imapserver.IMAPServer(self)
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 116, in __init__
    self.oauth2_client_id = repos.getoauth2_client_id()
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 332, in getoauth2_client_id
    )(self.account.getname())
TypeError: 'str' object is not callable
```

CLI options: `-o -d imap` for the error in the original post and `-o` for the stacktrace produced in this post

**Comment by nicolas33** [comment]
Looks like the documentation is not accurate. Please, try:

##### configuration

```
oauth2_client_id_eval = get_auth
```

##### python file

```
def get_auth(account):
    # account variable is the account name (str)
    output = check_output("pass Mail/" + account, shell=True)
    return output
```

**Comment by darnir** [comment]
I tried the following:

**Python FIle:**

```
def get_client_id(account):
    return check_output("pass Mail/" + account + "/XOATH2/client_id", shell=True)


def get_client_secret(account):
    return check_output("pass Mail/" + account + "/XOATH2/client_secret", shell=True)


def get_refresh_token(account):
    return check_output("pass Mail/" + account + "/XOATH2/refresh_token", shell=True)
```

**offlineimaprc**

```
oauth2_client_id_eval = get_client_id
oauth2_client_secret_eval = get_client_secret
oauth2_request_url = https://accounts.google.com/o/oauth2/token
oauth2_reresh_token_eval = get_refresh_token
```

I now get the following error:

```
Establishing connection to mail.stud.uni-saarland.de:993 (UdS-remote)
*** Processing account gmail
Establishing connection to imap.gmail.com:993 (gmail-remote)
XOAUTH2 authentication failed: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. k2mb429649232ldu']. Data: FEME2 AUTHENTICATE XOAUTH2

ERROR: All authentication types failed:
        XOAUTH2: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. k2mb429649232ldu']. Data: FEME2 AUTHENTICATE XOAUTH2

*** Finished account 'gmail' in 0:07
ERROR: Exceptions occurred during the run!
ERROR: All authentication types failed:
        XOAUTH2: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. k2mb429649232ldu']. Data: FEME2 AUTHENTICATE XOAUTH2


Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 271, in syncrunner
    self.__sync()
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 334, in __sync
    remoterepos.getfolders()
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 444, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 519, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 431, in __authn_helper
    "failed:\n\t%s"% msg, OfflineImapError.ERROR.REPO)
```

Or, when I use the `-d imap` option:

```
OfflineIMAP 7.0.5
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
Debug mode: Forcing to singlethreaded.
Now debugging for imap: IMAP protocol debugging
Now debugging for : Other offlineimap related sync messages
[imap]: Using authentication mechanisms ['XOAUTH2']
gmail
*** Processing account gmail
Establishing connection to imap.gmail.com:993 (gmail-remote)
[imap]: Attempting XOAUTH2 authentication
[imap]:   11:48.51 Account sync gmail last 20 log messages:
XOAUTH2 authentication failed: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. ba15mb114294429ldc']. Data: PKAA2 AUTHENTICATE XOAUTH2

ERROR: All authentication types failed:
        XOAUTH2: AUTHENTICATE command error: BAD ['Client aborted AUTHENTICATE command. ba15mb114294429ldc']. Data: PKAA2 AUTHENTICATE XOAUTH2

['  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 271, in syncrunner\n    self.__sync()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 334, in __sync\n    remoterepos.getfolders()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 444, in getfolders\n    imapobj = self.imapserver.acquireconnection()\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 519, in acquireconnection\n    self.__authn_helper(imapobj)\n', '  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 431, in __authn_helper\n    "failed:\\n\\t%s"% msg, OfflineImapError.ERROR.REPO)\n']
*** Finished account 'gmail' in 0:00

```

**Comment by nicolas33** [comment]
Are you sure to run on Py3? I'm seing Py2 traces.

I'll fix the configuration issue so that the eval option is more like the others.
Please try
```
def get_refresh_token(account):
    output = check_output("pass Mail/" + account + "/XOATH2/refresh_token", shell=True)
    print(output)
    return output
```
with the same logic for all functions to check returned values are correct.

**Comment by darnir** [comment]
You're right I was running Python2.

I moved to Python3 and now I have more issues. I'll deal with that a little later.
As you asked, making the change, I see that the right data is emitted by my function. It is in this form:

```
b'clientidhere.apps.googleusercontent.com\n'
```

**Comment by nicolas33** [comment]
Ok. Let try this:

```
def get_client_secret(account):
    output = check_output("pass Mail/" + account + "/XOATH2/client_secret", shell=True)
    output = output.encode('ascii').strip()
    return output
```

Play with both `encode()` and `strip()` alone if needed.

**Comment by nicolas33** [comment]
Oops, use `decode('ascii')` instead of `encode()`.

**Comment by darnir** [comment]
I tried both `decode('ascii')` and `decode('ascii').strip()`
The latter seems more correct since it does strip out an extra newline, but the above issue still persists

**Comment by nicolas33** [comment]
Does the credential work if it's configured outside of the eval option?

**Comment by darnir** [comment]
Yes

**Comment by nicolas33** [comment]
Please, move to https://gitter.im/OfflineIMAP/offlineimap to get more direct chat.

**Comment by nicolas33** [comment]
Hmm, we'll probably best strip the returned value by default.

**Comment by nicolas33** [comment]
Done.
