### ISSUE TITLE
offlineimap sync error on Mac OS X

### ISSUE THREAD

**Issue by fanpeng-kong** [OfflineIMAP/offlineimap#383]
#### General informations

- system/distribution (with version): Mac OS X El Capitan 10.11.6
- offlineimap version (`offlineimap -V`): offlineimap v7.0.8, imaplib2 v2.55 (bundled), Python v2.7.12
- Python version: Python v2.7.12
- server name or domain: imap.gmail.com
- CLI options: NA

#### Configuration file offlineimaprc

```
[general]
accounts = Gmail
maxsyncaccounts = 1
# pythonfile = ~/.offlineimap.py
ui=TTYUI

[Account Gmail]
localrepository = GmailLocal
remoterepository = GmailRemote
status_backend = sqlite
autorefresh = 5

[Repository GmailLocal]
ntype = Maildir
localfolders = ~/Maildir/Gmail

[Repository GmailRemote]
type = IMAP
remotehost = imap.gmail.com
remoteuser = kshark343@gmail.com
remotepass = blablabla
# remotepasseval = get_password_emacs("imap.gmail.com", "kshark345@gmail.com", "993")
ssl = yes
maxconnections = 3
realdelete = no

sslcacertfile = /usr/local/etc/openssl/cert.pem

folderfilter = lambda foldername: foldername in [
             'INBOX', '[Gmail]/Sent Mail', '[Gmail]/Drafts', '[Gmail]/Trash', '[Gmail]/All Mail']
```

#### pythonfile (if any)

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re
import os


def get_password_emacs(machine, login, port):
    s = "machine %s login %s port %s password ([^ ]*)\n" % (machine, login, port)
    p = re.compile(s)
    authinfo = os.popen("gpg -q --no-tty -d ~/.authinfo.gpg").read()
    return p.search(authinfo).group(1)
```

#### Logs, error

```
2016-10-13 11:28:05 INFO: OfflineImap 7.0.8 starting...
  Python: 2.7.12 Platform: darwin
  Args: /usr/local/Cellar/offlineimap/7.0.8/libexec/offlineimap.py -l Desktop/offlineimap.log
2016-10-13 11:28:05 WARNING: Thread 'Account sync Gmail' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/offlineimap/7.0.8/libexec/offlineimap/threadutil.py", line 163, in run
    Thread.run(self)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/offlineimap/7.0.8/libexec/offlineimap/accounts.py", line 257, in syncrunner
    self.localrepos  = Repository(self, 'local')
  File "/usr/local/Cellar/offlineimap/7.0.8/libexec/offlineimap/repository/__init__.py", line 67, in __new__
    repostype = config.get('Repository ' + name, 'type').strip()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'type' in section: 'Repository GmailLocal'


Last 2 debug messages logged for Account sync Gmail prior to exception:
thread: Register new thread 'Account sync Gmail' (account 'Gmail')
imap: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
```

#### Steps to reproduce the error
Originally I specify the password of my Gmail account in the `.offlineimaprc` file directly. And I can run the offlineimap CLI quite happily, and even integrate it with mu and mu4e in Emacs without a problem. Last night I read a post about [specifying the email account password in an encrypted file](https://gist.github.com/areina/3879626). However after I followed the instruction and tried to install 'gnupg21', I still can't make the encryption file work. So I decided to reverse back to my previous setup and change the 'gnupg21' to 'gnupg2' in Homebrew,  I found the offlineimap throw me this error. 

I have googled several similar problems and solutions, for example:
https://github.com/OfflineIMAP/offlineimap/issues/366
https://stackoverflow.com/questions/24675167/ca-certificates-mac-os-x
However none of them works for me. I did remember that I had a similar problem when I first set up offlineimap on my OS X, and solved it according to information in the second link in SO. 

Any suggestions would be appreciated.
- 
-

**Comment by fanpeng-kong** [comment]
Sorry my mistake. I found a typo in my 'offlineimaprc' file for the 'type'.
