### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)

### ISSUE THREAD

**Issue by antoyo** [OfflineIMAP/offlineimap#388]
#### General informations

- system/distribution (with version): ArchLinux (Linux 4.8.2-1-ARCH x86_64)
- offlineimap version (`offlineimap -V`): offlineimap v7.0.8, imaplib2 v2.55 (bundled), Python v2.7.12
- Python version: Python 2.7.12
- server name or domain: custom
- CLI options: none

#### pythonfile (if any)

```python
import subprocess
from subprocess import check_output

def get_pass(account):
    return check_output("pass mail/" + account, shell=True, stderr=subprocess.STDOUT).splitlines()[0]
```

#### Logs, error

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 271, in syncrunner
    self.__sync()
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 335, in __sync
    remoterepos.getfolders()
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 455, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 540, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 406, in __authn_helper
    if func(imapobj):
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 336, in __authn_plain
    imapobj.authenticate('PLAIN', self.__plainhandler)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 705, in authenticate
    typ, dat = self._simple_command('AUTHENTICATE', mechanism.upper())
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 1692, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 1418, in _command
    literal = literator(data, rqb)
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2283, in process
    ret = self.mech(self.decode(data))
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 195, in __plainhandler
    passwd = self.__getpassword()
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 169, in __getpassword
    self.password = self.repos.getpassword() or \
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 395, in getpassword
    return self.localeval.eval(passwd).encode('UTF-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
ERROR: While attempting to sync account 'XXXXX'
  'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
```

#### Steps to reproduce the error

- Run `offlineimap` with an account password containing special characters

I've fixed it by adding the following lines at the top (after the import) of `repository/IMAP.py` (it is probably a hack):
```python
reload(sys)
sys.setdefaultencoding("utf-8")
```
Could you please fix this issue?
Thanks.

I don't know if it is the same as #59 or #354.

**Comment by nicolas33** [comment]
> I've fixed it by adding the following lines at the top (after the import) of repository/IMAP.py (it is probably a hack):

Yes, it's a hack. setdefaultencoding is removed from the sys namespace for good reasons. I don't think there's a bug. I guess the root cause is that the password is encoded twice to UTF-8. Offlineimap expects unicode for the password.

Please, remove the hack and try the following in your python file:
```
def get_pass(account):
    return check_output("pass mail/" + account, shell=True, stderr=subprocess.STDOUT).splitlines()[0].decode('UTF-8')
```

**Comment by antoyo** [comment]
Thanks, it works with `decode`.

**Comment by celiomesquita** [comment]
*def Read(fname):
    ftext = open(fname, 'r+')
    content = ftext.read()
    ftext.close()
    return content.**decode('UTF-8')***

Worked with decode too.
