### ISSUE TITLE
Error when run offlineimaprc

### ISSUE THREAD

**Issue by yololetsplay** [OfflineIMAP/offlineimap#392]
Hi there :]

If I first run "offlineimaprc" I can the following error:

```
Traceback (most recent call last):
  File "/usr/bin/offlineimap", line 23, in <module>
    oi.run()
  File "/usr/lib/python2.7/dist-packages/offlineimap/init.py", line 46, in run
    options, args = self.parse_cmd_options()
  File "/usr/lib/python2.7/dist-packages/offlineimap/init.py", line 221, in parse_cmd_options
    config.set_if_not_exists('general','dry-run','False')
  File "/usr/lib/python2.7/dist-packages/offlineimap/CustomConfig.py", line 100, in set_if_not_exists
    self.set(section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 753, in set
    ConfigParser.set(self, section, option, value)
  File "/usr/lib/python2.7/ConfigParser.py", line 396, in set
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'general'
```

Can you help me with that?

Greetz,
yololetsplay

**Comment by nicolas33** [comment]
http://www.offlineimap.org/documentation.html#offlineimap
