### ISSUE TITLE
Python 2 ERROR: unhashable type: 'MaildirFolder'

### ISSUE THREAD

**Issue by potuz** [OfflineIMAP/offlineimap#393]
I am using Python2 instead of Python3 due to https://github.com/OfflineIMAP/offlineimap/issues/373
I hit that error when refreshing Trash in a postfix+dovecot account in my own server. 
#### General informations

- system/distribution (with version):  Gentoo 
- offlineimap version (`offlineimap -V`): 
offlineimap v7.0.8, imaplib2 v2.55 (bundled), Python v2.7.10
- Python version: 
- server name or domain:
myownserver 
- CLI options:
NULL 

#### Configuration file offlineimaprc
```
[general]

accounts = Acct1, Acct2, gmail
maxsyncaccounts = 3
pythonfile = ~/.offlineimap/offlineimap-gpg.py
fsync = false

[mbnames]
enabled = yes
filename = ~/.mutt/muttrc.mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"

[Account Acct1]
localrepository = acct1-local
remoterepository = acct1-remote
autorefresh = 24
#quick = 2
status_backend = sqlite

[Repository acct1-local]
type = Maildir
localfolders = ~/.mail/acct1
[Repository acct1-remote]
type = IMAP
remotepasseval = mailpasswd("acct1@server.net")
remotehost = imap.server.net
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
remoteuser = user1
idlefolders = ['INBOX']

[Account Acct2]
localrepository = acct2-local
remoterepository = acct2-remote
autorefresh = 24
#quick = 2
status_backend = sqlite

[Repository acct2-local]
type = Maildir
localfolders = ~/.mail/acct2
[Repository acct2-remote]
type = IMAP
remotepasseval = mailpasswd("acct2@server.net")
remotehost = imap.server.net
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
remoteuser = user2
idlefolders = ['INBOX']

[Account gmail]
localrepository = gmail-local
remoterepository = gmail-remote
autorefresh = 24
#quick = 2
postsynchook = /home/user/.mutt/postsync.sh
status_backend = sqlite

[Repository gmail-local]
type = Maildir
localfolders = ~/.mail/gmail

[Repository gmail-remote]

type = Gmail
remotepasseval = mailpasswd("user@gmail.com")
remotehost = imap.gmail.com
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
remoteuser = user@gmail.com
auth_mechanisms = GSSAPI, CRAM-MD5, PLAIN, LOGIN
idlefolders = ['INBOX']

folderfilter = lambda foldername: foldername in ['INBOX', '[Gmail]/Sent Mail', '[Gmail]/Drafts']
```
#### Logs, error
```
Folder Sent [acc: Acct1]:
 Syncing Sent: IMAP -> Maildir
Folder Trash [acc: Acct1]:
 Syncing Trash: IMAP -> Maildir
 Copy message UID 5 (1/1) acct1-remote:Trash -> acct1-local
 ERROR: while syncing Trash [account Acct1]
  unhashable type: 'MaildirFolder'
 ERROR: ERROR in syncfolder for Acct1 folder Trash: Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/offlineimap/accounts.py", line 584, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/lib64/python2.7/site-packages/offlineimap/folder/Base.py", line 1095, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib64/python2.7/site-packages/offlineimap/folder/Base.py", line 910, in __syncmessagesto_copy
    self.ui.copyingmessage(uid, num+1, num_to_copy, self, dstfolder)
  File "build/bdist.linux-x86_64/egg/offlineimap_notify.py", line 102, in new
    method(**{arg: old_args[arg] for arg in uibase_spec.args})
  File "build/bdist.linux-x86_64/egg/offlineimap_notify.py", line 127, in copyingmessage
    self.new_messages[account][destfolder].append(uid)
TypeError: unhashable type: 'MaildirFolder'

  unhashable type: 'MaildirFolder'
```
#### Steps to reproduce the error

- run offlineimap

**Comment by potuz** [comment]
Please disregard the issue as it might have been an issue with my own Python installation. Testing on a different client with essentially the same system does not produce the error. Will try recompiling python+offlineimap to check. Sorry for the noise.

**Comment by nicolas33** [comment]
Very weird. I agree with you that it's likely related to the python install. Otherwise, I think we'd have more complaints. The failing method is a core method call many times.

**Comment by potuz** [comment]
It is weird, I recompiled my installation of Python and offlineimap and I keep getting those errors. I guess it is my own installation, but I can't figure out where.

**Comment by nicolas33** [comment]
Python 2.7.10 is working fine here, if this helps.

**Comment by potuz** [comment]
Just to confirm this issue happened by my stupid mistake of having an alias to offlineimap-notify (a python script wrapper around offlineimap). It is offlineimap-notify which is failing with this version of offlineimap.
