### ISSUE TITLE
Offlineimap hangs forever frequently while IMAP <-> IMAP sync

### ISSUE THREAD

**Issue by cronfy** [OfflineIMAP/offlineimap#456]
Offlineimap hangs forever frequently while IMAP <-> IMAP sync.

I sync 2 IMAP mailboxes, basically I copy everything from old mailbox to new one. Mailbox is large: about 3.6G in ~5000 messages.

Every ~30 minutes it hangs at `[usem]` state (by `top`) and I need to kill and restart it.

There is timeout in config: 

```
socktimeout = 60
```
but it does not help.

Last time it happened I sent SIGQUIT, and here is a traceback:

```
Folder INBOX [acc: ***MASKED***]:
 ERROR: ERROR in syncfolder for ***MASKED*** folder INBOX: Traceback (most recent call last):
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/accounts.py", line 611, in syncfolder
    check_uid_validity()
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/accounts.py", line 473, in check_uid_validity
    if not localfolder.check_uidvalidity():
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/folder/Base.py", line 227, in check_uidvalidity
    return self.get_saveduidvalidity() == self.get_uidvalidity()
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/folder/IMAP.py", line 137, in get_uidvalidity
    self.imapserver.releaseconnection(imapobj)
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/imapserver.py", line 739, in releaseconnection
    connection.logout()
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/bundled_imaplib2.py", line 990, in logout
    self._close_threads()
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/bundled_imaplib2.py", line 1772, in _close_threads
    self.shutdown()
  File "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/bundled_imaplib2.py", line 609, in shutdown
    self.sock.shutdown(socket.SHUT_RDWR)
  File "/usr/local/lib/python2.7/ssl.py", line 802, in shutdown
    socket.shutdown(self, how)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 54] Connection reset by peer

  [Errno 54] Connection reset by peer
Folder Old.***MASKED*** [remote name ***MASKED***] [acc: ***MASKED***]:
 Syncing ***MASKED***: IMAP -> MappedIMAP


>>> HERE IS ^^^^ A STATE I FOUND IT <<<
>>> AND THEN I SENT SIGQUIT <<<

# Thread #0 (id=34479704064), Folder Old.***MASKED*** [remote name ***MASKED***] [acc: ***MASKED***]
File: "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner()
File: "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 224, in run ExitNotifyThread.run(self)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 160, in run Thread.run(self)
File: "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/accounts.py", line 604, in syncfolder localfolder.cachemessagelist()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/folder/UIDMaps.py", line 135, in cachemessagelist self._mb.cachemessagelist(min_date=min_date, min_uid=min_uid)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/folder/IMAP.py", line 254, in cachemessagelist imapobj = self.imapserver.acquireconnection()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/imapserver.py", line 487, in acquireconnection self.semaphore.acquire()
File: "/usr/local/lib/python2.7/threading.py", line 468, in acquire self.__cond.wait()
File: "/usr/local/lib/python2.7/threading.py", line 340, in wait waiter.acquire()

# Thread #1 (id=34479705088), Folder Old [remote name INBOX.Old] [acc: ***MASKED***]
File: "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner()
File: "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 224, in run ExitNotifyThread.run(self)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 160, in run Thread.run(self)
File: "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/accounts.py", line 604, in syncfolder localfolder.cachemessagelist()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/folder/UIDMaps.py", line 135, in cachemessagelist self._mb.cachemessagelist(min_date=min_date, min_uid=min_uid)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/folder/IMAP.py", line 254, in cachemessagelist imapobj = self.imapserver.acquireconnection()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/imapserver.py", line 487, in acquireconnection self.semaphore.acquire()
File: "/usr/local/lib/python2.7/threading.py", line 468, in acquire self.__cond.wait()
File: "/usr/local/lib/python2.7/threading.py", line 340, in wait waiter.acquire()

# Thread #2 (id=34477381632), mail.***MASKED***.ru handler
File: "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner()
File: "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File: "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/bundled_imaplib2.py", line 1805, in _handler line = self.inq.get(True, timeout)
File: "/usr/local/lib/python2.7/Queue.py", line 177, in get self.not_empty.wait(remaining)
File: "/usr/local/lib/python2.7/threading.py", line 359, in wait _sleep(delay)

# Thread #3 (id=34477378560), mail.***MASKED***.ru writer
File: "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner()
File: "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File: "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/bundled_imaplib2.py", line 2033, in _writer rqb = self.ouq.get()
File: "/usr/local/lib/python2.7/Queue.py", line 168, in get self.not_empty.wait()
File: "/usr/local/lib/python2.7/threading.py", line 340, in wait waiter.acquire()

# Thread #4 (id=34477377536), mail.***MASKED***.ru reader
File: "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner()
File: "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File: "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/bundled_imaplib2.py", line 1891, in _reader r = poll.poll(timeout)

# Thread #5 (id=34397275136), Sync Runner
File: "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner()
File: "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 160, in run Thread.run(self)
File: "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/init.py", line 63, in syncitall threads.wait() # Blocks until all accounts are processed.
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 71, in wait thread.join()
File: "/usr/local/lib/python2.7/threading.py", line 940, in join self.__block.wait()
File: "/usr/local/lib/python2.7/threading.py", line 340, in wait waiter.acquire()

# Thread #6 (id=34393318400), MainThread
File: "./offlineimap-7.1.0/offlineimap.py", line 26, in <module> oi.run()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/init.py", line 90, in run return self.__sync(options)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/init.py", line 467, in __sync threadutil.monitor()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 109, in monitor thread = exitedThreads.get(True, 60)
File: "/usr/local/lib/python2.7/Queue.py", line 177, in get self.not_empty.wait(remaining)
File: "/usr/local/lib/python2.7/threading.py", line 359, in wait _sleep(delay)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/init.py", line 437, in sig_handler stacktrace.dump(sys.stderr)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/utils/stacktrace.py", line 20, in dump for f, lno, name, line in traceback.extract_stack (stack):

# Thread #7 (id=34473145344), Account sync ***MASKED***
File: "/usr/local/lib/python2.7/threading.py", line 774, in __bootstrap self.__bootstrap_inner()
File: "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 224, in run ExitNotifyThread.run(self)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 160, in run Thread.run(self)
File: "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/accounts.py", line 281, in syncrunner self.__sync()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/accounts.py", line 390, in __sync thread.start()
File: "/home/***/imapcopy/offlineimap-7.1.0/offlineimap/threadutil.py", line 217, in start limitedNamespaces[self.limitNamespace].acquire()
File: "/usr/local/lib/python2.7/threading.py", line 468, in acquire self.__cond.wait()
File: "/usr/local/lib/python2.7/threading.py", line 340, in wait waiter.acquire()
```

Exit code was: 134

Hope this is useful.

#### General informations

offlineimap v7.1.0, imaplib2 v2.57 (bundled), Python v2.7.12
FreeBSD 10.3-STABLE

**Comment by nicolas33** [comment]
We can't tell much since you don't provide your configuration file. My best advice is you to carefully read all the configuration options available in https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf and take a look at the [known issues in the manual](http://www.offlineimap.org/doc/offlineimap.html).

There are ways to improve the reliability when hitting issues.

**Comment by nicolas33** [comment]
Do you aim at keeping both mailboxes in sync or is this a switch of mailbox? In the latter case, there might be other better suited tools like [imapsync](https://imapsync.lamiral.info/)

**Comment by cronfy** [comment]
I read all configuration options and Known Issues, but did not find anything matching except `socktimeout`.

I need to keep 2 IMAP mailboxes in sync for a while.

Here is my config:

```
[general]
pythonfile = ./helper.py
accounts = Thetest
socktimeout = 60


[Account Thetest]
localrepository = ThetestYandex
remoterepository = ThetestSph

# FROM
[Repository ThetestSph]
type = IMAP
remotehost = mail.***.ru
remoteuser = thetest@***.ru
remotepass = ***
cert_fingerprint = C8BD8D72B8B3FFF76D151F1CFA72A56074D446BF
ssl = yes
nametrans = SphToYandex
folderfilter = SphFolderFilter

# TO
[Repository ThetestYandex]
type = IMAP
remotehost = imap.yandex.ru
remoteuser = thetest@***.ru
remotepass = ***
ssl = yes
cert_fingerprint = 3C083981C3A851016AC18CB2CCE61ECD28A52AF9
nametrans = YandexToSph
folderfilter = YandexFolderFilter

```

**Comment by nicolas33** [comment]
> I read all configuration options and Known Issues, but did not find anything matching except socktimeout.

Try with `maxconnections = 1`. The singlethreadperfolder option could help, too.

**Comment by nicolas33** [comment]
I'm closing. Feel free to comment here and I'll re-open.
