### ISSUE TITLE
offlineimap segfaults

### ISSUE THREAD

**Issue by pmatos** [OfflineIMAP/offlineimap#538]
#### General informations

- system/distribution (with version): Fedora  27
- offlineimap version (`offlineimap -V`): 6.7.0
- Python version: 2.7.14
- server name or domain: 
- CLI options: -o

Coredump backtrace:

```
Core was generated by `/usr/bin/python /usr/bin/offlineimap -o'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  update_refs (containers=0x7fa25bcac440 <generations+96>) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Modules/gcmodule.c:400
400             gc->gc.gc_refs = Py_REFCNT(FROM_GC(gc));
[Current thread is 1 (Thread 0x7fa23e7fc700 (LWP 5340))]
Missing separate debuginfos, use: dnf debuginfo-install krb5-libs-1.15.2-7.fc27.x86_64 pcre2-10.31-3.fc27.x86_64
(gdb) bt
#0  update_refs (containers=0x7fa25bcac440 <generations+96>) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Modules/gcmodule.c:400
#1  collect () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Modules/gcmodule.c:998
#2  0x00007fa25b9bf3fd in collect_generations () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Modules/gcmodule.c:1124
#3  _PyObject_GC_Malloc () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Modules/gcmodule.c:1585
#4  0x00007fa25b98019b in PyType_GenericAlloc () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:781
#5  0x00007fa25b94a5e9 in BaseException_new () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/exceptions.c:34
#6  0x00007fa25b9809d5 in type_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:749
#7  0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#8  0x00007fa25b9f9767 in PyEval_CallObjectWithKeywords (func=func@entry=0x7fa25bc86440 <_PyExc_AttributeError>, arg=arg@entry=0x7fa22e105d50, kw=kw@entry=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4303
#9  0x00007fa25b9a46f2 in PyErr_NormalizeException () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/errors.c:192
#10 0x00007fa25b9ff3a9 in PyEval_EvalFrameEx (f=f@entry=0x7fa228ccb3d0, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3330
#11 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa25be85068, kwcount=0, defs=0x7fa25bd8f9f8, defcount=2, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#12 0x00007fa25b951c17 in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#13 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#14 0x00007fa25b94548e in instancemethod_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/classobject.c:2602
#15 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#16 0x00007fa25b9839f7 in slot_tp_init () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:5860
#17 0x00007fa25b980a54 in type_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:765
#18 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#19 0x00007fa25b9fe91f in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, pp_stack=0x7fa23e7f9050, func=0x563479d1b3b0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4748
#20 PyEval_EvalFrameEx (f=f@entry=0x7fa218003b10, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3107
#21 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa21c008308, kwcount=0, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#22 0x00007fa25ba00133 in fast_function (nk=0, na=<optimized out>, n=<optimized out>, pp_stack=0x7fa23e7f9228, func=0x7fa25bd5fcf8) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4529
#23 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7f9228) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4454
#24 PyEval_EvalFrameEx (f=f@entry=0x7fa21c008170, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#25 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa25be85068, kwcount=0, defs=0x7fa25bd60ba8, defcount=1, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#26 0x00007fa25b951c17 in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#27 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#28 0x00007fa25b94548e in instancemethod_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/classobject.c:2602
#29 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#30 0x00007fa25b9839f7 in slot_tp_init () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:5860
#31 0x00007fa25b980a54 in type_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:765
#32 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#33 0x00007fa25b9fe91f in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, pp_stack=0x7fa23e7f97b0, func=0x563479d247c0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4748
#34 PyEval_EvalFrameEx (f=f@entry=0x7fa23400a410, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3107
#35 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa24e34bd70, kwcount=0, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#36 0x00007fa25ba00133 in fast_function (nk=0, na=<optimized out>, n=<optimized out>, pp_stack=0x7fa23e7f9988, func=0x7fa25bd6c938) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4529
#37 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7f9988) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4454
#38 PyEval_EvalFrameEx (f=f@entry=0x7fa24e34bbc0, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#39 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa22f796cc8, kwcount=1, defs=0x7fa251ab21c8, defcount=4, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#40 0x00007fa25b951c17 in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#41 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#42 0x00007fa25b94548e in instancemethod_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/classobject.c:2602
#43 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#44 0x00007fa25b9839f7 in slot_tp_init () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:5860
#45 0x00007fa25b980a54 in type_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/typeobject.c:765
#46 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#47 0x00007fa25b9fe91f in ext_do_call (nk=<optimized out>, na=1, flags=<optimized out>, pp_stack=0x7fa23e7f9f10, func=0x563479d3fd30) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4748
#48 PyEval_EvalFrameEx (f=f@entry=0x7fa24e33d850, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3107
#49 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa22f796ec0, kwcount=1, defs=0x7fa251ab73c8, defcount=2, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#50 0x00007fa25b951c17 in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#51 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#52 0x00007fa25b9fe91f in ext_do_call (nk=<optimized out>, na=1, flags=<optimized out>, pp_stack=0x7fa23e7fa190, func=0x7fa251abb050) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4748
#53 PyEval_EvalFrameEx (f=f@entry=0x7fa2400de710, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3107
#54 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#55 0x00007fa25b951a7e in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#56 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#57 0x00007fa25b9fe91f in ext_do_call (nk=<optimized out>, na=2, flags=<optimized out>, pp_stack=0x7fa23e7fa410, func=0x7fa251abaa28) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4748
#58 PyEval_EvalFrameEx (f=f@entry=0x7fa2400de500, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3107
#59 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa22f796de8, kwcount=1, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#60 0x00007fa25b951c17 in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#61 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#62 0x00007fa25b9fe91f in ext_do_call (nk=<optimized out>, na=3, flags=<optimized out>, pp_stack=0x7fa23e7fa690, func=0x7fa251abb0c8) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4748
#63 PyEval_EvalFrameEx (f=f@entry=0x7fa24c4c9430, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3107
#64 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa218003878, kwcount=0, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#65 0x00007fa25ba00133 in fast_function (nk=0, na=<optimized out>, n=<optimized out>, pp_stack=0x7fa23e7fa868, func=0x7fa251aba6e0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4529
#66 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7fa868) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4454
#67 PyEval_EvalFrameEx (f=f@entry=0x7fa218003680, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#68 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa2180026d0, kwcount=0, defs=0x7fa250378168, defcount=1, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#69 0x00007fa25ba00133 in fast_function (nk=0, na=<optimized out>, n=<optimized out>, pp_stack=0x7fa23e7faa48, func=0x7fa2503488c0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4529
#70 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7faa48) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4454
#71 PyEval_EvalFrameEx (f=f@entry=0x7fa218002520, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#72 0x00007fa25ba00ab9 in fast_function (nk=<optimized out>, na=<optimized out>, n=2, pp_stack=0x7fa23e7fab68, func=0x7fa250348488) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4519
#73 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7fab68) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4454
#74 PyEval_EvalFrameEx (f=f@entry=0x7fa21c000db0, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#75 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x7fa25be85068, kwcount=0, defs=0x7fa250a46fe8, defcount=1, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#76 0x00007fa25b951c17 in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#77 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#78 0x00007fa25b9fe91f in ext_do_call (nk=<optimized out>, na=1, flags=<optimized out>, pp_stack=0x7fa23e7fadf0, func=0x7fa250a52398) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4748
#79 PyEval_EvalFrameEx (f=f@entry=0x7fa24e332cc8, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3107
#80 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#81 0x00007fa25b951a7e in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#82 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#83 0x00007fa25b94548e in instancemethod_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/classobject.c:2602
#84 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#85 0x00007fa25b9fe152 in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fa23e7fb2e8, func=0x7fa2207f83c0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4651
#86 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7fb2e8) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4456
#87 PyEval_EvalFrameEx (f=f@entry=0x7fa24c4cc638, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#88 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#89 0x00007fa25b951a7e in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#90 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#91 0x00007fa25b94548e in instancemethod_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/classobject.c:2602
#92 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#93 0x00007fa25b9fe152 in do_call (nk=<optimized out>, na=<optimized out>, pp_stack=0x7fa23e7fb7e8, func=0x7fa2207f80f0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4651
#94 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7fb7e8) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4456
#95 PyEval_EvalFrameEx (f=f@entry=0x7fa24c4cf220, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#96 0x00007fa25ba00ab9 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fa23e7fb908, func=0x7fa250a35c80) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4519
#97 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7fb908) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4454
#98 PyEval_EvalFrameEx (f=f@entry=0x7fa218000ee0, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#99 0x00007fa25ba00ab9 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fa23e7fba28, func=0x7fa25bd6e320) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4519
#100 call_function (oparg=<optimized out>, pp_stack=0x7fa23e7fba28) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4454
#101 PyEval_EvalFrameEx (f=f@entry=0x7fa2180008f0, throwflag=throwflag@entry=0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3068
#102 0x00007fa25ba03138 in PyEval_EvalCodeEx (co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:3666
#103 0x00007fa25b951a7e in function_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/funcobject.c:523
#104 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#105 0x00007fa25b94548e in instancemethod_call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/classobject.c:2602
#106 0x00007fa25b93ccb3 in PyObject_Call () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Objects/abstract.c:2547
#107 0x00007fa25b9f9767 in PyEval_CallObjectWithKeywords (func=0x7fa22fd7ea00, arg=0x7fa25be85050, kw=<optimized out>) at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Python/ceval.c:4303
#108 0x00007fa25ba10222 in t_bootstrap () at /usr/src/debug/python2-2.7.14-10.fc27.x86_64/Modules/threadmodule.c:620
#109 0x00007fa25b68350b in start_thread (arg=0x7fa23e7fc700) at pthread_create.c:465
#110 0x00007fa25ac6916f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by nicolas33** [comment]
v6.7.0 is more than 2 years old. Please, try v7.2.0.

**Comment by pmatos** [comment]
@nicolas33 thanks. quite ridiculous that F27 still ships such an old version. I will reopen if it reoccurs with more recent version.
