### ISSUE TITLE
non-existing mailbox on server makes account stop syncng

### ISSUE THREAD

**Issue by kalikaneko** [OfflineIMAP/offlineimap#55]
currently, after getting this error on one of the configured accounts, no more sync is done for the failed account. this could maybe just log an error and continue gracefully?

```python
 Hook return code: 1
 *** Finished account 'testaccount' in 0:37
 Next refresh in 5.0 minutes
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/offlineimap/imapserver.py", line 545, in idle
    raise e
OfflineImapError: Error SELECTing mailbox 'INBOX.Alerts', server reply:
('NO', ["Mailbox doesn't exist: INBOX.Alerts"])
```

**Comment by nicolas33** [comment]
The OP patch might need to be rewritten.
