### ISSUE TITLE
Traceback during docu generation

### ISSUE THREAD

**Issue by mimi1vx** [OfflineIMAP/offlineimap#560]
#### General informations

- system/distribution (with version): openSUSE Tumblewed
- offlineimap version (`offlineimap -V`): 7.2.0
- Python version: 2.7.5
- Python Sphinx 1.7.4

#### Logs, error
```
[    6s] asciidoc: writing: /home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs/offlineimap.xml
[    6s] asciidoc: include: /home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs/offlineimap.known_issues.txt
[    6s] asciidoc: offlineimap.txt: line 339: reading: /home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs/offlineimap.known_issues.txt
[    6s] 
[    6s] a2x: executing: "xmllint" --nonet --noout --valid "/home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs/offlineimap.xml"
[    6s] 
[    6s] 
[    6s] a2x: chdir /home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs
[    6s] a2x: executing: "xsltproc"  --stringparam callout.graphics 0 --stringparam navig.graphics 0 --stringparam admon.textlabel 1 --stringparam admon.graphics 0  "/etc/asciidoc/docbook-xsl/manpage.xsl" "/home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs/offlineimap.xml"
[    6s] 
[    6s] Warn: meta author : no refentry/info/author                        offlineimap
[    6s] Note: meta author : see http://www.docbook.org/tdg5/en/html/autho  offlineimap
[    6s] Warn: meta author : no author data, so inserted a fixme            offlineimap
[    6s] Note: Writing offlineimap.1
[    6s] 
[    6s] a2x: chdir /home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs
[    6s] a2x: deleting /home/abuild/rpmbuild/BUILD/offlineimap-7.2.0/docs/offlineimap.xml
[    7s] reading sources... [100%] ui
[    7s] 
[    7s] WARNING: autodoc: failed to import data u'ui' from module 'offlineimap.accounts'; the following exception was raised:
[    7s] Traceback (most recent call last):
[    7s]   File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 164, in import_object
[    7s]     obj = attrgetter(obj, attrname)
[    7s]   File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc/__init__.py", line 274, in get_attr
[    7s]     return autodoc_attrgetter(self.env.app, obj, name, *defargs)
[    7s]   File "/usr/lib/python2.7/site-packages/sphinx/ext/autodoc/__init__.py", line 1509, in autodoc_attrgetter
[    7s]     return safe_getattr(obj, name, *defargs)
[    7s]   File "/usr/lib/python2.7/site-packages/sphinx/util/inspect.py", line 220, in safe_getattr
[    7s]     raise AttributeError(name)
[    7s] AttributeError: ui
[    7s] 

```

#### Steps to reproduce the error

try build offlineimap package

**Comment by nicolas33** [comment]
I cannot reproduce this error. What command do you type?

**Comment by mimi1vx** [comment]
https://build.opensuse.org/package/view_file/server:mail/offlineimap/offlineimap.spec?expand=1
-->
```
python setup.py build
make %{?_smp_mflags} V=1 -C docs
```

**Comment by nicolas33** [comment]
Out of topic: the line "Suggests:       python2-gssapi" is not up-to-date in the spec file.

Looks like you didn't edited the source code. I wonder this could be because of the version of sphinx. Here, I have:
```
> sphinx-build --version
Sphinx (sphinx-build) 1.3.1
```

**Comment by nicolas33** [comment]
> ?? if is python-gssapi optional I think a better tag is Suggests than Recommends or Requires..

My bad, this is correct. We moved away from pykerberos, not the other way around.

What's your sphinx version?

**Comment by mimi1vx** [comment]
1.7.4 last stable


Dne pá 15. 6. 2018 14:21 uživatel Nicolas Sebrecht <notifications@github.com>
napsal:
