### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by damon-kwok** [OfflineIMAP/offlineimap#567]
#### General informations

- system/distribution (with version): Cygwin 2.893
- offlineimap version (`offlineimap -V`): none
- Python version: 2.7.14

#### Logs, error
```
pip install --user offlineimap
Collecting offlineimap
  Using cached https://files.pythonhosted.org/packages/e6/8c/5c986f3f8f48a10f8dd648eab521416616a4ccb179ef1fa2a46882976a29/offlineimap-7.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "d:\cygwin\tmp\pip-install-fcmhr9\offlineimap\setup.py", line 26, in <module>
        import offlineimap
      File "offlineimap\__init__.py", line 20, in <module>
        from offlineimap.init import OfflineImap
      File "offlineimap\init.py", line 34, in <module>
        from offlineimap import threadutil, accounts, folder, mbnames
      File "offlineimap\accounts.py", line 27, in <module>
        from offlineimap.repository import Repository
      File "offlineimap\repository\__init__.py", line 25, in <module>
        from offlineimap.repository.IMAP import IMAPRepository, MappedIMAPRepository
      File "offlineimap\repository\IMAP.py", line 28, in <module>
        from offlineimap import folder, imaputil, imapserver, OfflineImapError
      File "offlineimap\folder\__init__.py", line 1, in <module>
        from . import Base, Gmail, IMAP, Maildir, LocalStatus, UIDMaps
      File "offlineimap\folder\Gmail.py", line 24, in <module>
        from offlineimap import imaputil, imaplibutil, OfflineImapError
      File "offlineimap\imaplibutil.py", line 18, in <module>
        import fcntl
    ImportError: No module named fcntl

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in d:\cygwin\tmp\pip-install-fcmhr9\offlineimap\
```

**Comment by nicolas33** [comment]
`fcntl` is packaged with python2 on linux. It looks like it's different on cygwin. You should look at your python install on cygwin.

**Comment by chris001** [comment]
@damon-kwok 
* You're supposed to **install python for cygwin**, not **python for windows**.  Python for cygwin is compiled to use cygwin libraries and support (`fcntl` is included and works).
* The simplest way to install python inside cygwin is to install the python package right at the beginning of the cygwin windows installer.  
* Cygwin windows installer lets you install into Cygwin programming languages: Ruby, PHP, Python ,etc.
* Once you install python into cygwin with the cygwin installer, open a cygwin terminal window, and type `python --version` to verify it's installed inside cygwin and works.

**Comment by damon-kwok** [comment]
@chris001 @nicolas33 thanks,i see
