### ISSUE TITLE
Looking for a way to end quitting on exceptions as it trashes the oAuth2 tokens

### ISSUE THREAD

**Issue by Elv13** [OfflineIMAP/offlineimap#578]
#### General informations

A major showstopper I have every time I try to setup offlineimap is that it will always crash at some point and the oauth2 token will expire and it wont be able to restart. This renders offlineimap useless to me because it can't be relied on to keep the maildirs updated. I really don't want to disable security on the account and use passwords.

I am looking for a way to stop offlineimap from quitting on python exceptions and or to keep itself alive and stop forcing me to ssh into that server and open a browser and generate new tokens a dozen time per day.

If there is a better way not to have to regenerate tokens manually, I am all for it. If it exists, consider adding to the documentation and sorry for the noise.

#### Configuration file offlineimaprc

(some variables are set by the `run.sh` script using Docker secrets

```
[general]
accounts = GMail
# ui = Blinkenlights
socktimeout = 120

[mbnames]
enabled = yes
filename = ~/Mutt/muttrc.mailboxes
header = "mailboxes "
peritem = "+%(accountname)s/%(foldername)s"
sep = " "
footer = "\n"

[Account GMail]
localrepository = LocalExample
remoterepository = RemoteExample
synclabels = no
autorefresh = 0.5
quick = 10
ignorelabels = \Inbox, \Starred, \Sent, \Draft, \Spam, \Trash, \Important, \Gmail\Important

[Repository LocalExample]
type = Maildir
localfolders = ~/GMail
nametrans = lambda folder: {'drafts':   '[Gmail]/Drafts',
                            'sent':     '[Gmail]/Sent Mail',
                            'important':'[Gmail]/Important',
                            'spam':     '[Gmail]/Spam',
                            'starred':  '[Gmail]/Starred',
                            'trash':    '[Gmail]/Trash',
                            'archive':  '[Gmail]/All Mail',
                            }.get(folder, folder)

[Repository GmailLocalExample]
type = GmailMaildir

# Go to https://console.developers.google.com/apis/credentials
# create a project, click credentials
# git clone https://github.com/google/gmail-oauth2-tools
# run:
#    python2 gmail-oauth2-tools/python/oauth2.py --generate_oauth2_token \
#    --client_id=<the text ending with .apps.googleusercontent.com> \
#    --client_secret=<secret> 
#
# Do what it says, enter the codes below:

[Repository RemoteExample]
type = IMAP
ssl = yes
retrycount = 200
realdelete = no
remoteport = 993
keepalive = 60
holdconnectionopen = yes
remotehost = imap.gmail.com
maxconnections = 10
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
oauth2_request_url = https://accounts.google.com/o/oauth2/token
nametrans = lambda folder: {'[Gmail]/Drafts':    'drafts',
                            '[Gmail]/Sent Mail': 'sent',
                            '[Gmail]/Starred':   'flagged',
                            '[Gmail]/Important':   'important',
                            '[Gmail]/Spam':   'spam',
                            '[Gmail]/Trash':     'trash',
                            '[Gmail]/All Mail':  'archive',
                            }.get(folder, folder)
folderfilter = lambda folder: folder not in ['[Gmail]/Important',
                                             '[Gmail]/Starred',
                                             ]

# If called with the docker script, this will be changed automatically
remoteuser = YOUR_EMAIL
oauth2_client_id = YOUR_CLIENT_ID
oauth2_client_secret = YOUR_CLIENT_SECRET
oauth2_access_token = YOUR_ACCESS_TOKEN
oauth2_refresh_token = YOUR_SECRET

```

#### pythonfile (if any)

```
FROM debian:stretch
MAINTAINER Emmanuel Lepage Vallee <elv1313+bugs@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
RUN cat /etc/apt/sources.list | sed 's/deb /deb-src /' >> /etc/apt/sources.list
RUN apt-get -qq update --fix-missing
RUN apt-get install -y bash git
RUN apt-get install -y wget nano python-requests-oauthlib
RUN apt-get install -y python-oauthlib ca-certificates
RUN apt-get build-dep offlineimap -y

RUN useradd -m offlineimap
ADD run.sh /home/offlineimap/run.sh
RUN chmod 755 /home/offlineimap/run.sh

RUN chown -R offlineimap:users /home/offlineimap/

ADD offlineimaprc /home/offlineimap/.offlineimaprc
RUN chown offlineimap:offlineimap /home/offlineimap/.offlineimaprc

USER offlineimap

RUN cd /home/offlineimap/ && git clone https://github.com/OfflineIMAP/offlineimap.git


# Use exec mode so offlineimap can receive SIGUSR2
ENTRYPOINT ["/home/offlineimap/run.sh"]
```

run.sh:

```
#! /bin/sh

alias offlineimap="/home/offlineimap/offlineimap/offlineimap.py"

sed -i "s/YOUR_EMAIL/$EMAIL/" /home/offlineimap/.offlineimaprc
sed -i "s/YOUR_CLIENT_ID/$CLIENT_ID/" /home/offlineimap/.offlineimaprc
sed -i "s/YOUR_ACCESS_TOKEN/$ACCESS_TOKEN/" /home/offlineimap/.offlineimaprc
sed -i "s=YOUR_SECRET=$SECRET=" /home/offlineimap/.offlineimaprc
sed -i "s=YOUR_CLIENT_SECRET=$CLIENT_SECRET=" /home/offlineimap/.offlineimaprc

if [ ! -e '~/.offlineimap' ]; then
    mkdir -p /home/offlineimap/GMail/.offlineimap
    ln -s /home/offlineimap/GMail/.offlineimap ~
fi

mkdir -p /home/offlineimap/GMail/Mutt
ln -s /home/offlineimap/GMail/Mutt ~/

while true; do
    exec /home/offlineimap/offlineimap/offlineimap.py \
         -c /home/offlineimap/.offlineimaprc
done
```

#### Logs, error

```
Folder INBOX [acc: GMail]:
 Copy message UID 8544 (577/49125) RemoteExample:INBOX -> LocalExample:INBOX
Thread 'Copy message from RemoteExample:[Gmail]/All Mail' terminated with exception:
Traceback (most recent call last):
  File "/home/offlineimap/offlineimap/offlineimap/threadutil.py", line 160, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/offlineimap/offlineimap/offlineimap/folder/Base.py", line 839, in copymessageto
    message = self.getmessage(uid)
  File "/home/offlineimap/offlineimap/offlineimap/folder/IMAP.py", line 324, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/home/offlineimap/offlineimap/offlineimap/folder/IMAP.py", line 784, in _fetch_from_imap
    imapobj.select(self.getfullIMAPname(), readonly=True)
  File "/home/offlineimap/offlineimap/offlineimap/imaplibutil.py", line 70, in select
    raise OfflineImapError(errstr, severity)
OfflineImapError: Error SELECTing mailbox '[Gmail]/All Mail', server reply:
('NO', ['System Error (Failure)'])

```

#### Steps to reproduce the error

Run the Dockerfile and wait long enough with enough (6 figures) mail.

**Comment by nicolas33** [comment]
Please try with the current "next" branch.

**Comment by Elv13** [comment]
I have been running it since a week and it seems more stable. Still the feature request still stands, it should try to recover on errors instead of quitting. It still quits when wifi goes down or resume from suspend.

As a workaround, I updated the files above with an out-of-process `sed` magic to refresh the tokens in case offlineimap goes down. It's a hack, but it helps.
