### ISSUE TITLE
list.remove(x) failure following AUTHENTICATIONFAILED

### ISSUE THREAD

**Issue by benfitzg** [OfflineIMAP/offlineimap#585]
#### General informations

- system/distribution (with version): v7.2.1 hash 11313a9b9c684ee23d631db9fec1a615ec6bc76a
- offlineimap version (`offlineimap -V`): 7.2.1
- Python version: Python 2.7.13
- server name or domain: n/a
- CLI options: python2 offlineimap -c offlineimap.rc -u basic

#### Logs, error

Syncing Programming/Ideas: IMAP -> Maildir
Establishing connection to imap.gmail.com:993 (gmail)
ERROR: command: APPEND => no response after 90.0 secs
Establishing connection to imap.gmail.com:993 (gmail)
XOAUTH2 authentication failed: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
ERROR: Copying message -1 [acc: gmail]
  list.remove(x): x not in list
ERROR: while syncing Personal.School [account gmail]
  list.remove(x): x not in list
ERROR: ERROR in syncfolder for gmail folder Personal/School: Traceback (most recent call last):
  File "/home/ben/apps/offlineimap/lib/offlineimap/accounts.py", line 646, in syncfolder
    localfolder.syncmessagesto(remotefolder, statusfolder)
  File "/home/ben/apps/offlineimap/lib/offlineimap/folder/Base.py", line 1116, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/home/ben/apps/offlineimap/lib/offlineimap/folder/Base.py", line 944, in __syncmessagesto_copy
    self.copymessageto(uid, dstfolder, statusfolder, register=0)
  File "/home/ben/apps/offlineimap/lib/offlineimap/folder/Base.py", line 844, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/home/ben/apps/offlineimap/lib/offlineimap/folder/IMAP.py", line 759, in savemessage
    self.imapserver.releaseconnection(imapobj)
  File "/home/ben/apps/offlineimap/lib/offlineimap/imapserver.py", line 741, in releaseconnection
    self.assignedconnections.remove(connection)
ValueError: list.remove(x): x not in list

  list.remove(x): x not in list
Syncing Programming/Internet: IMAP -> Maildir

#### Steps to reproduce the error
Run offlineimap and wait

**Comment by benfitzg** [comment]
To add - it's also unfortunate that the error doesn't cause the process to exit as I run under systemd so at least a failure can be restarted. As it is, it just hangs.

**Comment by nicolas33** [comment]
Could you try the current "next" branch please? I wonder this could be related to XOAUTH2 renewing the connection. We have a patch about this here: https://github.com/OfflineIMAP/offlineimap/tree/next

**Comment by benfitzg** [comment]
So far so good. I have had timeouts but it rode through them and continued to sync. Thanks!

**Comment by nicolas33** [comment]
Thank you much for the feedback.
