### ISSUE TITLE
UNIQUE constraint failed

### ISSUE THREAD

**Issue by pmatos** [OfflineIMAP/offlineimap#630]
#### General informations

- system/distribution (with version): arch linux
- offlineimap version (`offlineimap -V`):  7.3.0
- Python version:  2.7.16
- server name or domain: mail.igalia.com
- CLI options: -a Igalia

#### Logs, error

```
Copy message from IgaliaRemote:buildroot:
 ERROR: Copying message 6936 [acc: Igalia]
  UNIQUE constraint failed: status.id while inserting UID 6936
Thread 'Copy message from IgaliaRemote:buildroot' terminated with exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/threadutil.py", line 160, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 852, in copymessageto
    statusfolder.savemessage(new_uid, message, flags, rtime)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 362, in savemessage
    exc_info()[2])
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 357, in savemessage
    (uid,flags,mtime,labels))
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 183, in __sql_write
    self.connection.execute(sql, args)
UserWarning: UNIQUE constraint failed: status.id while inserting UID 6936


Last 4 debug messages logged for Copy message from IgaliaRemote:buildroot prior to exception:
thread: Register new thread 'Copy message from IgaliaRemote:buildroot' (account 'Igalia')
imap: Returned object from fetching 6936: 'Return-path: <buildroot-bounces@busybox.net>
Envelope-to: pmatos@igalia.com
Delivery-date: Fri, 30 Aug 2019 15:51:09 +0200
Received: from fanzine.loca...tp://lists.busybox.net/mailman/listinfo/buildroot
'
maildir: Write mail 'buildroot:6936' with flags set([])
maildir: savemessage: returning uid 6936
ERROR: Exceptions occurred during the run!
ERROR: Copying message 6936 [acc: Igalia]
  UNIQUE constraint failed: status.id while inserting UID 6936

Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 852, in copymessageto
    statusfolder.savemessage(new_uid, message, flags, rtime)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 362, in savemessage
    exc_info()[2])
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 357, in savemessage
    (uid,flags,mtime,labels))
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 183, in __sql_write
    self.connection.execute(sql, args)
```

#### Description

Haven't had a problem with offlineimap and my current configuration until I tried to sync today and got this error. It repeats itself no matter how many times I try to run offlineimap. Is there a way out of this now?

**Comment by nicolas33** [comment]
The immediate fix is to use [copy_ignore_eval](https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf#L1375).

Later, you might like to manually edit the sqlite database and remove the offending UID.

**Comment by edi9999** [comment]
This happened to me as well after doing the following : 

- I was using offlineimap for multiple years without a problem

- today, I decided to have my email on my phone and setup my iPhone to sync my emails (with the standard iphone mail app)

Now, when I try to do a sync, I also get the following message : 

```
  ('UNIQUE constraint failed: status.id while inserting UID 4388', <traceback object at 0x7efbff0a4a80>)
```

**Comment by titaniumbones** [comment]
hi @edi9999 this was an issue for me as well; I think it's a db corruption issue whose real solution is to remove the offending record from the database.  But you can use the `copy_ignore_eval` line  from the link with the erroring ID; just place the lambda in your remote repository configuration in .offlineimaprc.  This will allow everything else to download until you have a chance to fix the database directly (which requires using the CLI).
