### ISSUE TITLE
Crash wen retrying message download

### ISSUE THREAD

**Issue by hramrach** [OfflineIMAP/offlineimap#647]
#### General informations

- system/distribution (with version):  openSUSE Leap 15.1
- offlineimap version (`offlineimap -V`):  7.1.5
- Python version:  2.7.14

#### Configuration file offlineimaprc

```
[general]
metadata = ~/.offlineimap
accounts = suse.de
ui = ttyui
# ui = basic
socktimeout = 300
[Account suse.de]
localrepository = suse.de-Local
remoterepository = suse.de-Remote

autorefresh = 0.5
[Repository suse.de-Local]
type = Maildir
localfolders = ~/Mail/suse.de
sync_deletes = no
utime_from_header = yes
filename_use_mail_timestamp = yes

[Repository suse.de-Remote]
type = IMAP
remotehost = imap.suse.de
ssl = yes
# sslcacertfile = OS-DEFAULT
sslcacertfile = /etc/ssl/ca-bundle.pem
# tls_level = tls_secure
# ssl_version = ssl23
remoteuser = user
# idlefolders = ['INBOX']
maxconnections = 1
holdconnectionopen = yes
keepalive = 30
expunge = no
sync_deletes = no
```

#### Logs, error

```
 *** Finished account 'suse.de' in 1:07                                
 *** Processing account suse.de                                                                                      
Folder INBOX [acc: suse.de]:                                                                                         
 Syncing INBOX: IMAP -> Maildir                                        
 Copy message UID 763816 (1/3) suse.de-Remote:INBOX -> suse.de-Local   
Copy message from suse.de-Remote:INBOX:                                
 ERROR: Server shutting down.. While fetching msg '763816' in folder 'INBOX'. Query: (BODY.PEEK[]) Retrying (1/2)
Folder INBOX [acc: suse.de]:                                           
 Copy message UID 763817 (2/3) suse.de-Remote:INBOX -> suse.de-Local   
Copy message from suse.de-Remote:INBOX:                                
 Establishing connection to imap.suse.de:993 (suse.de-Remote)          
 ERROR: Copying message 763816 [acc: suse.de]                          
  list.remove(x): x not in list                                        
Folder INBOX [acc: suse.de]:                                           
 Copy message UID 763818 (3/3) suse.de-Remote:INBOX -> suse.de-Local   
Thread 'Copy message from suse.de-Remote:INBOX' terminated with exception:
Traceback (most recent call last):                                     
  File "/usr/lib/python2.7/site-packages/offlineimap/threadutil.py", line 160, in run
    Thread.run(self)                                                   
  File "/usr/lib64/python2.7/threading.py", line 754, in run           
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 839, in copymessageto
    message = self.getmessage(uid)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 324, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 810, in _fetch_from_imap
    self.imapserver.releaseconnection(imapobj)
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 739, in releaseconnection
    self.assignedconnections.remove(connection)
ValueError: list.remove(x): x not in list

```

#### Steps to reproduce the error

run offlineimap until it retries a message download

**Comment by nicolas33** [comment]
This was a known issue with old versions. Please, upgrade to v7.3.2.

**Comment by hramrach** [comment]
Upgrading to current version resolved the problem, thanks

**Comment by hramrach** [comment]
Problem persists with offlineimap 7.3.2 

ERROR: While attempting to sync account 'suse.de'                                                
  [Errno 107] Transport endpoint is not connected                                                      
                                                                                                 
Traceback:                                                                                             
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 293, in syncrunner                                                                                        
    self.__sync()                                                                                
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 369, in __sync                 
    remoterepos.getfolders()                                                                     
  File "/usr/lib/python2.7/site-packages/offlineimap/repository/IMAP.py", line 452, in getfolders                                                                                 
    imapobj = self.imapserver.acquireconnection()                                                
  File "/usr/lib/python2.7/site-packages/offlineimap/imapserver.py", line 572, in acquireconnection                                                                               
    af=self.af,                                                                                        
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 202, in __init__                                                                                       
    super(WrappedIMAP4_SSL, self).__init__(*args, **kwargs)                                            
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2190, in __init__                                                                                 
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)                                                                                       
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 359, in __init__                                                                                  
    self.open(host, port)                                                                        
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 210, in open                
    super(WrappedIMAP4_SSL, self).open(host, port)                                               
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 2203, in open                                                                                     
    self.ssl_wrap_socket()                                                                       
  File "/usr/lib/python2.7/site-packages/offlineimap/bundled_imaplib2.py", line 563, in ssl_wrap_socket                                                                           
    cert_err = self.cert_verify_cb(self.sock.getpeercert(), self.host)                                 
  File "/usr/lib64/python2.7/ssl.py", line 688, in getpeercert                                   
    if not self._sslobj or not _ssl.HAS_ALPN:                                                          
  File "/usr/lib64/python2.7/ssl.py", line 648, in _check_connected                              
    else:                                                                                              
  File "/usr/lib64/python2.7/socket.py", line 228, in meth                                             
    return getattr(self._sock,name)(*args)                                                       
                                                                                                       
ERROR: command: UID => no response after 300.0 secs. While fetching msg '888694' in folder 'INBOX'. Query: (BODY.PEEK[]) Retrying (1/2)                                           
ERROR: Copying message 888694 [acc: suse.de]                                                           
  list.remove(x): x not in list

**Comment by nicolas33** [comment]
Is this issue reproducible? If so does it fail for the same UID?

**Comment by hramrach** [comment]
It is not easily reproducible.

I think it is triggered by the server being down and rejecting connection rather than simple timeout now.
