### ISSUE TITLE
ERROR: source object is already set

### ISSUE THREAD

**Issue by zuku81** [OfflineIMAP/offlineimap#675]
#### General informations

- system/distribution (with version): Ubuntu 20.04 LTS
- offlineimap version (`offlineimap -V`):  7.3.3
- Python version: 2.7
- server name or domain: 
- CLI options: offlineimap --dry-run -l /root/.offlineimap.log

#### Logs, error

root@offlineimap:~# offlineimap --dry-run -l /root/.offlineimap.log
OfflineIMAP 7.3.3
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.101 (bundled), Python v2.7.18rc1, OpenSSL 1.1.1f  31 Mar 2020
ERROR: source object is already set
ERROR: Exceptions occurred during the run!
ERROR: source object is already set

#### Steps to reproduce the error

- 
- 

I'm just trying to move Offlineimap configuration to the new server, but I have such error as above. I don't know how to troubleshoot this because I do not have anything in log.

**Comment by chris001** [comment]
Please post back with output from: 
`python --version`

**Comment by zuku81** [comment]
root@offlineimap:~# python --version
Python 2.7.18rc1

**Comment by chris001** [comment]
1.   Could you try to git bisect this? http://offlineimap.org/doc/git-bisect.html

2. Also, what's your configuration file?  Note: Redact/remove private info such as server addresses and passwords.

**Comment by nicolas33** [comment]
`--dry-run` mode is known to have issues. Do you hit this without this option?

**Comment by zuku81** [comment]
root@offlineimap:~# offlineimap -l /root/.offlineimap.log
OfflineIMAP 7.3.3
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.101 (bundled), Python v2.7.18rc1, OpenSSL 1.1.1f  31 Mar 2020
ERROR: source object is already set
ERROR: Exceptions occurred during the run!
ERROR: source object is already set

**Comment by zuku81** [comment]
----------------.offlineimapprc-------------------------------
# Sample minimal config file.  Copy this to ~/.offlineimaprc and edit to
# suit to get started fast.

[general]
# Path to file with arbitrary Python code to be loaded
pythonfile = ~/.offlineimap.py
accounts = WP, Polanica

[Account WP]
localrepository = WPlocal
remoterepository = Gmail-wp

[Repository WPlocal]
#readonly = true
#sslcacertfile = /etc/ssl/certs/ca-certificates.crt
cert_fingerprint = 2e4efe27a24ffc61ea0c5ccc9145fb5e4ef8c6af
type = IMAP
remotehost = imap.wp.pl
remoteport = 993
ssl = yes
createfolders = false
remoteuser = ***************
#remotepasseval = get_pass()
remotepasseval = unencrypt_password("~/.offlineimappass")
folderfilter = lambda folder: folder in ['INBOX', 'Xpertis', 'Citibank', 'Mbank', 'Trenowanie', 'Wys&AUI-ane']
nametrans = lambda folder:<----> re.sub  ('INBOX', 'WP',
<------><------>re.sub ('Xpertis', 'WP/Xpertis',
<------><------>re.sub ('Citibank', 'WP/Citibank',
<------><------>re.sub ('Mbank', 'WP/Mbank',
<------><------>re.sub ('Trenowanie', 'WP/Trenowanie',
<------><------>re.sub ('Wys&AUI-ane', 'WP/Wys&AUI-ane', folder))))))


[Repository Gmail-wp]
auth_mechanisms  = PLAIN
type = Gmail
ssl = yes
#createfolders = false
#realdelete = true
# Synchronize only the folders Inbox and Sent:
folderfilter = lambda folder: folder in ['WP', 'WP/Xpertis', 'WP/Citibank', 'WP/Mbank', 'WP/Trenowanie', 'WP/Wys&AUI-ane']
#folderincludes =  ['WP', 'WP/Xpertis', 'WP/Citibank', 'WP/Mbank', 'WP/Trenowanie', 'WP/Wys&AUI-ane']
remotehost = imap.gmail.com
remoteuser = ************************
#remotepasseval = get_pass()
remotepasseval = unencrypt_password("~/.offlineimappassgoogletwoway")
cert_fingerprint = cb7bcaea2c188c39c2c91e5f6f6fbe949df29ad0
#sslcacertfile = /etc/ssl/certs/ca-certificates.crt
nametrans = lambda folder:<----> re.sub ('WP', 'INBOX',
<------><------>re.sub ('WP/Xpertis', 'Xpertis',
<------><------>re.sub ('WP/Citibank', 'Citibank',
<------><------>re.sub ('WP/Mbank', 'Mbank',
<------><------>re.sub ('WP/Trenowanie', 'Trenowanie',
<------><------>re.sub ('WP/Wys&AUI-ane', 'Wys&AUI-ane', folder))))))

---------------------------------------------EOF--------------------------------------------------------------

**Comment by zuku81** [comment]
root@offlineimap:~# cd offlineimap/
root@offlineimap:~/offlineimap# git bisect start
root@offlineimap:~/offlineimap# git bisect good
root@offlineimap:~/offlineimap# git bisect bad
7531ac4640aff8477b0893c55c99c9fe4a9bbcfc was both good and bad
root@offlineimap:~/offlineimap# git bisect skip
7531ac4640aff8477b0893c55c99c9fe4a9bbcfc was both good and bad
root@offlineimap:~/offlineimap# git bisect reset
Already on 'master'
Your branch is up to date with 'origin/master'.
root@offlineimap:~/offlineimap#

**Comment by chris001** [comment]
Please post again your (redacted) config file, and precede it with three backticks alone on a line, and followed by three backticks alone on a line, to preserve formatting, as demonstrated here:
https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by nicolas33** [comment]
I've edited the posts as requested.

**Comment by zuku81** [comment]
anyone have any idea how to resolve this issue?

**Comment by zuku81** [comment]
How to troubleshoot this error during messages sync?

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 160, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 839, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/UIDMaps.py", line 234, in getmessage
    return self._mb.getmessage(self.r2l[uid])
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 324, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 810, in _fetch_from_imap
    self.imapserver.releaseconnection(imapobj)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imapserver.py", line 763, in releaseconnection
    self.assignedconnections.remove(connection)
ValueError: list.remove(x): x not in list


Last 6 debug messages logged for Copy message from WPlocal:INBOX prior to exception:
thread: Register new thread 'Copy message from WPlocal:INBOX' (account 'WP')
imap: WPlocal: level 'tls_compat', version 'None'
imap: Attempting PLAIN authentication
imap: __plainhandler: returning wojzuk@wp.pl(passwd hidden for log)
imap: Attempting LOGIN authentication
imap: Attempting IMAP LOGIN authentication
ERROR: Exceptions occurred during the run!
ERROR: command: APPEND => socket error: <class 'socket.error'> - [Errno 104] Connection reset by peer

Traceback:
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 661, in savemessage
    imaputil.flagsmaildir2imap(flags), date, content)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/bundled_imaplib2.py", line 718, in append
    return self._simple_command(name, mailbox, flags, date_time, **kw)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/bundled_imaplib2.py", line 1748, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/bundled_imaplib2.py", line 1498, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/bundled_imaplib2.py", line 200, in get_response
    raise typ(exc_fmt % str(val))

ERROR: command: UID => socket error: <type 'exceptions.IOError'> - Too many read 0. While fetching msg '10549' in folder 'INBOX'. Query: (BODY.PEEK[]) Retrying (1/2)
ERROR: Copying message -4553 [acc: WP]
  list.remove(x): x not in list

Traceback:
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 839, in copymessageto
    message = self.getmessage(uid)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/UIDMaps.py", line 234, in getmessage
    return self._mb.getmessage(self.r2l[uid])
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 324, in getmessage
    data = self._fetch_from_imap(str(uid), self.retrycount)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/IMAP.py", line 810, in _fetch_from_imap
    self.imapserver.releaseconnection(imapobj)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imapserver.py", line 763, in releaseconnection
    self.assignedconnections.remove(connection)
