### ISSUE TITLE
RC on PyPI

### ISSUE THREAD

**Issue by holmboe** [OfflineIMAP/offlineimap#68]
The only release of offlineimap available on the Python Package Index (http://pypi.python.org) is a release candidate.

This renders the package non-installable without using ``--pre`` to allow pre-releases.

```bash
hh@mail:~$ pip install --user offlineimap
Downloading/unpacking offlineimap
  Could not find a version that satisfies the requirement offlineimap (from versions: 6.5.5-rc2)
Cleaning up...
No distributions matching the version for offlineimap
Storing complete log in /home/hh/.pip/pip.log
hh@mail:~$ cat .pip/pip.log 
Downloading/unpacking offlineimap

  Getting page https://pypi.python.org/simple/offlineimap/
  URLs to search for versions for offlineimap:
  * https://pypi.python.org/simple/offlineimap/
  Analyzing links from page https://pypi.python.org/simple/offlineimap/
    Found link https://pypi.python.org/packages/source/o/offlineimap/offlineimap-6.5.5-rc2.tar.gz#md5=cdef488bc0c188a6cf15bf7dd060abd1 (from https://pypi.python.org/simple/offlineimap/), version: 6.5.5-rc2
  Ignoring link https://pypi.python.org/packages/source/o/offlineimap/offlineimap-6.5.5-rc2.tar.gz#md5=cdef488bc0c188a6cf15bf7dd060abd1 (from https://pypi.python.org/simple/offlineimap/), version 6.5.5-rc2 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement offlineimap (from versions: 6.5.5-rc2)

Cleaning up...

  Removing temporary dir /tmp/pip_build_hh...
No distributions matching the version for offlineimap

Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/index.py", line 309, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for offlineimap
```

**Comment by nicolas33** [comment]
Pypi is missing of contributors to propagate releases. Sorry.
Contributions are welcome, BTW. ,-)
