### ISSUE TITLE
TypeError while printing error in IMAP.py

### ISSUE THREAD

**Issue by jakkdl** [OfflineIMAP/offlineimap#712]
#### General informations

- system/distribution (with version): Arch Linux
- offlineimap version (`offlineimap -V`): 
- `offlineimap v8.0.0, imaplib2 v3.06, Python v3.10.1, OpenSSL 1.1.1m  14 Dec 2021`
- CLI options: None

#### Logs, error

```
Folder All Mail [acc: main]:
 ERROR: while syncing All Mail [account main]
  sequence item 0: expected str instance, bytes found
 ERROR: ERROR in syncfolder for main folder All Mail: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/offlineimap/accounts.py", line 666, in syncfolder
    localfolder.syncmessagesto(remotefolder, statusfolder)
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/Base.py", line 1164, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/Base.py", line 1114, in __syncmessagesto_flags
    dstfolder.addmessagesflags(uids, set(flag))
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/IMAP.py", line 995, in addmessagesflags
    self.__addmessagesflags_noconvert(uidlist, flags)
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/IMAP.py", line 987, in __addmessagesflags_noconvert
    self.__processmessagesflags('+', uidlist, flags)
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/IMAP.py", line 1054, in __processmessagesflags
    self.__processmessagesflags_real(operation,
  File "/usr/lib/python3.10/site-packages/offlineimap/folder/IMAP.py", line 1019, in __processmessagesflags_real
    'Error with store: %s' % '. '.join(response[1]),
TypeError: sequence item 0: expected str instance, bytes found

  sequence item 0: expected str instance, bytes found

```

#### Steps to reproduce the error

- I have no clue really, I'm just starting to play around with neomutt+notmuch and I deleted a bunch of emails, and as a newb to offlineimap and CLI mail handling it would take me a while to dig into it, but regardless it feels like a pretty silly coding error and that this error message should handle ... the error and print it. Or if this function really shouldn't receieve a bytes objects, then handle the problem further up in order to print a helpful error message.

**Comment by nicolas33** [comment]
This legacy project works with py2 only. There's offlineimap3 for python3.
