### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by azazar** [OfflineIMAP/offlineimap#715]
#### General informations

- system/distribution (with version): python:3.11.0a5-alpine3.15 Docker Image
- offlineimap version (`offlineimap -V`): v7.3.4, imaplib2 v2.101 (bundled), Python v3.11.0a5, OpenSSL 1.1.1l  24 Aug 2021
- Python version: 3.11.0a5
- server name or domain: gmail.com
- CLI options: -c /dev/stdin

#### Configuration file `$HOME/.offlineimaprc`

```
[general]
accounts = my.account@gmail.com

[Account my.account@gmail.com]
localrepository = my.account@gmail.com-local
remoterepository = my.account@gmail.com-repo

synclabels = yes

labelsheader = X-Keywords


[Repository my.account@gmail.com-local]
type = GmailMaildir

localfolders = ~/Mail/my.account@gmail.com

[Repository my.account@gmail.com-repo]
type = Gmail
remoteuser = my.account@gmail.com
remotepass = ***********

sslcacertfile = OS-DEFAULT
```

#### stdout/stderr

```
OfflineIMAP 7.3.4
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v2.101 (bundled), Python v3.11.0a5, OpenSSL 1.1.1l  24 Aug 2021
Thread 'Account sync ********@gmail.com' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/offlineimap/threadutil.py", line 159, in run
    Thread.run(self)
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/threading.py", line 968, in run
    self._target(*self._args, **self._kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/accounts.py", line 278, in syncrunner
    self.remoterepos = Repository(self, 'remote')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/repository/__init__.py", line 84, in __new__
    return repo(name, account)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/repository/Gmail.py", line 33, in __init__
    IMAPRepository.__init__(self, reposname, account)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/repository/IMAP.py", line 42, in __init__
    self.imapserver = imapserver.IMAPServer(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/imapserver.py", line 95, in __init__
    self.sslcacertfile = repos.getsslcacertfile()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/repository/IMAP.py", line 260, in getsslcacertfile
    cacertfile = get_os_sslcertfile()
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/utils/distro.py", line 88, in get_os_sslcertfile
    l = get_os_sslcertfile_searchpath()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/utils/distro.py", line 68, in get_os_sslcertfile_searchpath
    OS = get_os_name()
         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/offlineimap/utils/distro.py", line 49, in get_os_name
    DISTRO = platform.linux_distribution()[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'platform' has no attribute 'linux_distribution'


Last 2 debug messages logged for Account sync *******@gmail.com prior to exception:
thread: Register new thread 'Account sync *******@gmail.com' (account '*******@gmail.com')
imap: Using authentication mechanisms ['GSSAPI', 'XOAUTH2', 'CRAM-MD5', 'PLAIN', 'LOGIN']
```

#### Steps to reproduce the error

- Create Docker container with following Dockerfile

```
FROM python:3.11.0a5-alpine3.15

# Install specific packages
RUN pip3 install offlineimap

# Update certificates
RUN apk --no-cache add ca-certificates \
  && update-ca-certificates

# Run OfflineIMAP
CMD sed 's/= *~/= \/mnt\/home/' /mnt/home/.offlineimaprc | offlineimap -c /dev/stdin
```

- Launch it with `$HOME/.offlineimaprc` configured to copy from GMail to local repo. Command is `docker build -t offlineimap . && docker run -it -v "$HOME":/mnt/home offlineimap:latest`

**Comment by Kodiologist** [comment]
This issue probably belongs in https://github.com/OfflineIMAP/offlineimap3 instead.
