### ISSUE TITLE
command: FETCH => socket error: <class 'OSError'> - Too many read 0

### ISSUE THREAD

**Issue by alexmihajlov** [OfflineIMAP/offlineimap#726]
#### General informations

- system/distribution (with version): OpenBSD 7.2
- offlineimap version (`offlineimap -V`): offlineimap v8.0.0, imaplib2 v3.06, Python v3.9.15, LibreSSL 3.6.0
- Python version: Python v3.9.15
- server name or domain: N/A
- CLI options: 

#### Configuration file offlineimaprc

```
[general]
ui = basic
accounts = MyExchangeServer
fsync = false
maxsyncaccounts = 1
singlethreadperfolder = false
holdconnectionopen = yes
ssl_version = StartTLS
usecompression = yes
keepalive = 60

[Account MyExchangeServer]
localrepository = MyExchangeServer-Local
remoterepository = MyExchangeServer-Remote
autorefresh = 0.5
quick = 10
utf8foldernames = yes

[Repository MyExchangeServer-Local]
type = Maildir
localfolders = ~/.Mail/MyExchangeServer

[Repository MyExchangeServer-Remote]
type = IMAP
remotehost = mail.myserver.org
remoteport = 993
remoteuser = user
remotepass = pass
realdelete = no
maxconnections = 1
ssl = yes
sslcacertfile = /etc/ssl/cert.pem
keepalive = 6
auth_mechanisms = PLAIN, LOGIN
```

#### pythonfile (if any)

```
N/A
```

#### Logs, error

```
Establishing connection to mail.myserver.org:993 (MyExchangeServer-Remote)
Syncing outages: IMAP -> Maildir
Syncing removal: IMAP -> Maildir
Syncing Remstats: IMAP -> Maildir
ERROR: ERROR in syncfolder for MyExchangeServer folder Remstats: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/offlineimap/accounts.py", line 653, in syncfolder
    remotefolder.cachemessagelist()
  File "/usr/local/lib/python3.9/site-packages/offlineimap/folder/IMAP.py", line 299, in cachemessagelist
    res_type, response = imapobj.fetch(
  File "/usr/local/lib/python3.9/site-packages/imaplib2/imaplib2.py", line 828, in fetch
    return self._simple_command(name, message_set, message_parts, **kw)
  File "/usr/local/lib/python3.9/site-packages/imaplib2/imaplib2.py", line 1705, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/local/lib/python3.9/site-packages/imaplib2/imaplib2.py", line 1449, in _command_complete
    typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
  File "/usr/local/lib/python3.9/site-packages/imaplib2/imaplib2.py", line 212, in get_response
    raise typ(exc_fmt % str(val))
imaplib2.imaplib2.IMAP4.abort: command: FETCH => socket error: <class 'OSError'> - Too many read 0

  command: FETCH => socket error: <class 'OSError'> - Too many read 0
Syncing root mail: IMAP -> Maildir

```

#### Steps to reproduce the error

trying to get mail from a mailbox with 25,000 emails
- 
-

**Comment by alexmihajlov** [comment]
please close, wrong version

**Comment by adambeatrimble** [comment]
what do you mean wrong version? did you use the wrong version of imaplib2 or python? Only asking because I have a similar issue except with the IDLE command
