### ISSUE TITLE
errors for python during launch offlineimap firts time 

### ISSUE THREAD

**Issue by Ayanashi** [OfflineIMAP/offlineimap#731]
```
#### General informations

- Archlinux 6.2.12-arch1-1: 
-  offlineimap v8.0.0, imaplib2 v3.06, Python v3.10.10, OpenSSL 3.0.8 7 Feb 2023: 
- Python v3.10.10: 
- -: 
- -: 

```
```
#### Configuration file offlineimaprc
[general]
accounts = Gmail
maxsyncaccounts = 3

[Account Gmail]
localrepository = Local
remoterepository = Remote

[Repository Local]
type = Maildir
localfolders = ~/Maildir

[Repository Remote]
type = IMAP
remotehost = imap.gmail.com
remoteuser = *******
remotepass = ******
ssl = yes
maxconnections = 1
```

```
#### Logs, error
Traceback (most recent call last):
  File "/usr/bin/offlineimap", line 22, in <module>
    oi.run()
  File "/usr/lib/python3.10/site-packages/offlineimap/init.py", line 98, in run
    options, args = self.__parse_cmd_options()
  File "/usr/lib/python3.10/site-packages/offlineimap/init.py", line 229, in __parse_cmd_options
    config.read(configfilename)
  File "/usr/lib/python3.10/configparser.py", line 699, in read
    self._read(fp, filename)
  File "/usr/lib/python3.10/configparser.py", line 1087, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
--
File "/usr/lib/python3.10/site-packages/offlineimap/accounts.py", line 298, in syncrunner
    self.__sync()
  File "/usr/lib/python3.10/site-packages/offlineimap/accounts.py", line 375, in __sync
    remoterepos.getfolders()
  File "/usr/lib/python3.10/site-packages/offlineimap/repository/IMAP.py", line 681, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/lib/python3.10/site-packages/offlineimap/imapserver.py", line 560, in acquireconnection
    imapobj = imaplibutil.WrappedIMAP4_SSL(
  File "/usr/lib/python3.10/site-packages/offlineimap/imaplibutil.py", line 207, in __init__
    super(WrappedIMAP4_SSL, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/imaplib2/imaplib2.py", line 2124, in __init__
    IMAP4.__init__(self, host, port, debug, debug_file, identifier, timeout, debug_buf_lvl)
  File "/usr/lib/python3.10/site-packages/imaplib2/imaplib2.py", line 357, in __init__
    self.open(host, port)
  File "/usr/lib/python3.10/site-packages/offlineimap/imaplibutil.py", line 211, in open
    raise OfflineImapError("No CA certificates "
```
```

#### Steps to reproduce the error

- $ offlineimap

**Comment by chris001** [comment]
You have to create an `.offlineimaprc` file with your email account login information, etc.

How to create basic config file:  https://www.offlineimap.org/doc/quick_start.html
Examples : https://www.offlineimap.org/doc/conf_examples.html
All config options: https://github.com/OfflineIMAP/offlineimap/blob/master/offlineimap.conf
