### ISSUE TITLE
stopped working recently 

### ISSUE THREAD

**Issue by homonto** [OfflineIMAP/offlineimap#735]
All was working and suddenly stopped - I am not sure when and why

- system/distribution (with version):  debian 11 on proxmox
- offlineimap version (`offlineimap -V`):  offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.2, OpenSSL 1.1.1n  15 Mar 2022
- Python version: Python 3.9.2

OfflineIMAP 7.3.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
ERROR: Exceptions occurred during the run!
ERROR: while syncing INBOX [account xxx@xxx]
  ('UNIQUE constraint failed: status.id while inserting UID 1182', <traceback object at 0x7f34a04a0b80>)

Traceback:
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 1086, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 895, in __syncmessagesto_copy
    statusfolder.savemessage(uid, None, flags, rtime)
  File "/usr/share/offlineimap3/offlineimap/folder/LocalStatusSQLite.py", line 352, in savemessage
    raise UserWarning("%s while inserting UID %s" %

ERROR: ERROR in syncfolder for xxxx@xxxxx folder : Traceback (most recent call last):
  File "/usr/share/offlineimap3/offlineimap/folder/LocalStatusSQLite.py", line 349, in savemessage
    self.__sql_write('INSERT INTO status (id,flags,mtime,labels) VALUES (?,?,?,?)',
  File "/usr/share/offlineimap3/offlineimap/folder/LocalStatusSQLite.py", line 178, in __sql_write
    self.connection.execute(sql, args)
sqlite3.IntegrityError: UNIQUE constraint failed: status.id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 658, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 1086, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 895, in __syncmessagesto_copy
    statusfolder.savemessage(uid, None, flags, rtime)
  File "/usr/share/offlineimap3/offlineimap/folder/LocalStatusSQLite.py", line 352, in savemessage
    raise UserWarning("%s while inserting UID %s" %
UserWarning: ('UNIQUE constraint failed: status.id while inserting UID 1182', <traceback object at 0x7f34a04a0b80>)

  ('UNIQUE constraint failed: status.id while inserting UID 1182', <traceback object at 0x7f34a04a0b80>)

**Comment by homonto** [comment]
sorted out - problem was I moved from ext4 to samba cifs the folders and meta folder does not like it
