### ISSUE TITLE
IMAPFolder.selectro() should probably have a retry mechanism

### ISSUE THREAD

**Issue by aspiers** [OfflineIMAP/offlineimap#9]
Occasionally the Groupwise IMAP server I sync with returns a `NO` response when offlineimap tries to `EXAMINE` a folder:

```
Thread 'Copy message from full:in/review' terminated with exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/threadutil.py", line 156, in run
    Thread.run(self)
  File "/usr/lib64/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 330, in copymessageto
    message = self.getmessage(uid)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/IMAP.py", line 214, in getmessage
    imapobj.select(self.getfullname(), readonly = True)
  File "/usr/lib/python2.7/site-packages/offlineimap/imaplibutil.py", line 63, in select
    raise OfflineImapError(errstr, severity)
OfflineImapError: Error SELECTing mailbox 'in/review', server reply:
('NO', ['EXAMINE (C042)'])
```

It is clear from this [error codes reference document](http://www.novell.com/documentation/nwec/pdfdoc/nwec/nwec.pdf) that `C042` is usually a transitory error caused by another client modifying the same folder.  Therefore it would make sense for offlineimap to surround this IMAP operation with a simple exponential backoff / retry mechanism.  After a maximum number of retries are exceeded it could then bubble up the exception as per normal.

**Comment by nicolas33** [comment]
I didn't check when it was implemented but the fetch strategy has a retry mechanism.
