### ISSUE TITLE
file creation fails during sync with gmail (on raspbian)

### ISSUE THREAD

**Issue by axelGschaider** [OfflineIMAP/offlineimap#99]
Hi

I'm using a fairly standard config file to sync with gmail. Syncing with this config file still works on my company computer (Ubuntu, offlineimap 6.5.4, python 2.7.5 ).

On my raspberry pi (raspbian, python 2.7.3) there is an older version of offlineimap in the repos (it 6.3.x I guess) and it failed complaining about an empty exc_info ( I can reproduce the error message but currently I have another version installed ). I cloned the git repo (dev branch) and installed system wide.
Got this error message:
```
Licensed under the GNU GPL v2+ (v2 or any later version)
Account sync Gmail:
 *** Processing account Gmail
 Establishing connection to imap.gmail.com:993
Folder [Gmail]/All Mail [acc: Gmail]:
 Syncing [Gmail]/All Mail: Gmail -> Maildir
Folder [Gmail]/Bin [acc: Gmail]:
 Syncing [Gmail]/Bin: Gmail -> Maildir
Folder [Gmail]/Drafts [acc: Gmail]:
 Syncing [Gmail]/Drafts: Gmail -> Maildir
Folder [Gmail]/Bin [acc: Gmail]:
 Establishing connection to imap.gmail.com:993
Folder [Gmail]/Drafts [acc: Gmail]:
 Establishing connection to imap.gmail.com:993
 Copy message 15216 (1 of 2) Gmail-Remote:[Gmail]/Drafts -> Gmail-Local
 Copy message 15353 (2 of 2) Gmail-Remote:[Gmail]/Drafts -> Gmail-Local
Copy message from Gmail-Remote:[Gmail]/Drafts:
 ERROR: Copying message 15353 [acc: Gmail]
  'exceptions.OSError' object has no attribute 'EEXIST'
Thread 'Copy message from Gmail-Remote:[Gmail]/Drafts' terminated with exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 158, in run
    Thread.run(self)
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Gmail.py", line 277, in copymessageto
    super(GmailFolder, self).copymessageto(uid, dstfolder, statusfolder, register)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 603, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Maildir.py", line 318, in savemessage
    tmpname = self.save_to_tmp_file(messagename, content)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Maildir.py", line 274, in save_to_tmp_file
    if e.errno == e.EEXIST:
AttributeError: 'exceptions.OSError' object has no attribute 'EEXIST'


Last 3 debug messages logged for Copy message from Gmail-Remote:[Gmail]/Drafts prior to exception:
thread: Register new thread 'Copy message from Gmail-Remote:[Gmail]/Drafts' (account 'Gmail')
imap: Returned object from fetching 15353: 'MIME-Version: 1.0
Received: by 10.112.63.71 with HTTP; Fri, 23 May 2014 02:44:44 -0700 (PDT)
To: alber
Date: Fri, 23 May 2014 11:44:44 +0200
Message-I..."ltr"><br></div>

--f46d0408d7d74ee25304fa0e1478--'
maildir: Write mail '[Gmail].Drafts:15353' with flags set(['S'])
ERROR: Exceptions occurred during the run!
ERROR: Copying message 15353 [acc: Gmail]
  'exceptions.OSError' object has no attribute 'EEXIST'

Traceback:
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Base.py", line 603, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Maildir.py", line 318, in savemessage
    tmpname = self.save_to_tmp_file(messagename, content)
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/folder/Maildir.py", line 274, in save_to_tmp_file
    if e.errno == e.EEXIST:

Exception in thread imap.gmail.com reader (most likely raised during interpreter shutdown):Exception in thread imap.gmail.com handler (most likely raised during interpreter shutdown):Exception in thread Folder [Gmail]/Bin [acc: Gmail] (most likely raised during interpreter shutdown):Exception in thread imap.gmail.com reader (most likely raised during interpreter shutdown):


Traceback (most recent call last):Traceback (most recent call last):
Traceback (most recent call last):Exception in thread imap.gmail.com handler (most likely raised during interpreter shutdown):


Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run


  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 229, in run  File "/usr/lib/python2.7/threading.py", line 505, in run
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1793, in _reader


  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 158, in run  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1793, in _reader<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exc_info'  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1677, in _handler

  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/lib/python2.7/threading.py", line 505, in run<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exc_info'
```

Removed the installation, ~/.offlineimap and all my previously downloaded mail data. Did `git checkout v6.5.2.1`, reinstalled and got a fairly similar error:
```
ERROR: Exceptions occurred during the run!
ERROR: [Errno 22] Invalid argument: '/home/agl/mail/gmail/INBOX/tmp/1404204474_0.18081.ruegen,U=12289,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S'
Exception in thread imap.gmail.com handler (most likely raised during interpreter shutdown):Exception in thread imap.gmail.com reader (most likely raised during interpreter shutdown):Exception in thread imap.gmail.com reader (most likely raised during interpreter shutdown):
 Exception in thread Folder Schuettelreime [acc: Gmail] (most likely raised during interpreter shutdown):Exception in thread imap.gmail.com handler (most likely raised during interpreter shutdown):
Traceback (most recent call last):Exception in thread imap.gmail.com handler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_innerTraceback (most recent call last):


Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
Traceback (most recent call last):


  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 226, in run
  File "/usr/lib/python2.7/threading.py", line 505, in run  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner

  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1658, in _handler
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/threadutil.py", line 155, in run  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1773, in _reader  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1773, in _reader
  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1658, in _handler
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exc_info'

  File "/usr/local/lib/python2.7/dist-packages/offlineimap/imaplib2.py", line 1658, in _handler
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'exc_info'
```

Also tried to do the same with version 6.5.4 (the same as in my work). Again an error.

All errors lead to `exc_info`. But the main difference between my installment at my work computer and the raspberry pi is a minor python version number ( as noted above: 2.7.5 vs 2.7.3 ) and . . . well . . . the hardware. Any help/ideas?

**Comment by gatl** [comment]
I seem to have this problem that showed up suddenly. I am runing 6.6.1 on Arch Linux on a btrfs filesystem if it helps.

```
Traceback:
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 876, in __syncmessagesto_copy
    register = 0)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Gmail.py", line 287, in copymessageto
    super(GmailFolder, self).copymessageto(uid, dstfolder, statusfolder, register)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 792, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Maildir.py", line 368, in savemessage
    tmpname = self.save_to_tmp_file(messagename, content)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Maildir.py", line 304, in save_to_tmp_file
    if e.errno == e.EEXIST:

 ERROR: ERROR in syncfolder for gmail folder inbox: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/offlineimap/accounts.py", line 567, in syncfolder
    remotefolder.syncmessagesto(localfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 1046, in syncmessagesto
    action(dstfolder, statusfolder)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 876, in __syncmessagesto_copy
    register = 0)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Gmail.py", line 287, in copymessageto
    super(GmailFolder, self).copymessageto(uid, dstfolder, statusfolder, register)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Base.py", line 792, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Maildir.py", line 368, in savemessage
    tmpname = self.save_to_tmp_file(messagename, content)
  File "/usr/lib/python2.7/site-packages/offlineimap/folder/Maildir.py", line 304, in save_to_tmp_file
    if e.errno == e.EEXIST:
AttributeError: 'exceptions.OSError' object has no attribute 'EEXIST'

  'exceptions.OSError' object has no attribute 'EEXIST'
```

**Comment by nicolas33** [comment]
See 36375daee67e8dd1a8256abec6798618f4e05061. Please test the current `next` branch.

This might not be the end of the story because we won't retry anymore. I have no idea why we have 7 retries, BTW.

**Comment by gatl** [comment]
It did not work, but it provided a much better error message:
`OSError: [Errno 30] Read-only file system`
Problem solved! My bad. I'm sorry for the trouble.

**Comment by nicolas33** [comment]
Great!
